package com.realtech.socialsurvey.compute.common;

public final class EmailConstants
{
    private EmailConstants()
    {}

    public static final String EMAIL_TYPE_REGISTRATION_INVITATION_MAIL = "REGISTRATION_INVITATION_MAIL";
    public static final String EMAIL_TYPE_NEW_REGISTRATION_INVITATION_MAIL = "NEW_REGISTRATION_INVITATION_MAIL";
    public static final String EMAIL_TYPE_COMPANY_REGISTRATION_STAGE_MAIL = "COMPANY_REGISTRATION_STAGE_MAIL";
    public static final String EMAIL_TYPE_AGENT_SURVEY_REMINDER_MAIL = "AGENT_SURVEY_REMINDER_MAIL";
    public static final String EMAIL_TYPE_RESET_PASSWORD_EMAIL = "RESET_PASSWORD_EMAIL";
    public static final String EMAIL_TYPE_INVITATION_TO_SOCIALSURVEY_ADMIN_EMAIL = "INVITATION_TO_SOCIALSURVEY_ADMIN_EMAIL";
    public static final String EMAIL_TYPE_SUBSCRIPTION_CHARGE_UNSUCCESSFUL_EMAIL = "SUBSCRIPTION_CHARGE_UNSUCCESSFUL_EMAIL";
    public static final String EMAIL_TYPE_EMAIL_VERIFICATION_MAIL = "EMAIL_VERIFICATION_MAIL";
    public static final String EMAIL_TYPE_EMAIL_VERIFICATION_REQUESTMAIL_TO_ADMIN_MAIL = "EMAIL_VERIFICATION_REQUESTMAIL_TO_ADMIN_MAIL";
    public static final String EMAIL_TYPE_EMAIL_VERIFIED_NOTIFICATION_MAIL = "EMAIL_VERIFIED_NOTIFICATION_MAIL";
    public static final String EMAIL_TYPE_EMAIL_VERIFIED_NOTIFICATION_MAIL_TO_ADMIN_MAIL = "EMAIL_VERIFIED_NOTIFICATION_MAIL_TO_ADMIN_MAIL";
    public static final String EMAIL_TYPE_VERIFICATION_MAIL = "VERIFICATION_MAIL";
    public static final String EMAIL_TYPE_REGISTRATION_COMPLETION_EMAIL = "REGISTRATION_COMPLETION_EMAIL";
    public static final String EMAIL_TYPE_FATAL_EXCEPTION_EMAIL = "FATAL_EXCEPTION_EMAIL";
    public static final String EMAIL_TYPE_EMAILSENDING_FAILURE_MAIL = "EMAILSENDING_FAILURE_MAIL";
    public static final String EMAIL_TYPE_RETRY_CHARGE_EMAIL = "RETRY_CHARGE_EMAIL";
    public static final String EMAIL_TYPE_RETRY_EXHAUSTED_EMAIL = "RETRY_EXHAUSTED_EMAIL";
    public static final String EMAIL_TYPE_ACCOUNT_DISABLED_MAIL = "ACCOUNT_DISABLED_MAIL";
    public static final String EMAIL_TYPE_ACCOUNT_DELETION_MAIL = "ACCOUNT_DELETION_MAIL";
    public static final String EMAIL_TYPE_ACCOUNT_UPGRADE_MAIL = "ACCOUNT_UPGRADE_MAIL";
    public static final String EMAIL_TYPE_DEFAULT_SURVEY_COMPLETION_MAIL = "DEFAULT_SURVEY_COMPLETION_MAIL";
    public static final String EMAIL_TYPE_DEFAULT_SURVEY_COMPLETION_UNPLEASANT_MAIL = "DEFAULT_SURVEY_COMPLETION_UNPLEASANT_MAIL";
    public static final String EMAIL_TYPE_DEFAULT_SURVEY_REMINDER_MAIL = "DEFAULT_SURVEY_REMINDER_MAIL";
    public static final String EMAIL_TYPE_SURVEY_REMINDER_MAIL = "SURVEY_REMINDER_MAIL";
    public static final String EMAIL_TYPE_SURVEY_COMPLETION_TO_ADMINS_AND_AGENT_MAIL = "SURVEY_COMPLETION_TO_ADMINS_AND_AGENT_MAIL";
    public static final String EMAIL_TYPE_DEFAULT_SOCIAL_POST_REMINDER_MAIL = "DEFAULT_SOCIAL_POST_REMINDER_MAIL";
    public static final String EMAIL_TYPE_CONTACT_US_MAIL = "CONTACT_US_MAIL";
    public static final String EMAIL_TYPE_DEFAULT_SURVEY_INVITATION_MAIL = "DEFAULT_SURVEY_INVITATION_MAIL";
    public static final String EMAIL_TYPE_SURVEY_INVITATION_MAIL = "SURVEY_INVITATION_MAIL";
    public static final String EMAIL_TYPE_ACCOUNT_BLOCKING_MAIL = "ACCOUNT_BLOCKING_MAIL";
    public static final String EMAIL_TYPE_ACCOUNT_REACTIVATION_MAIL = "ACCOUNT_REACTIVATION_MAIL";
    public static final String EMAIL_TYPE_SUBSCRIPTION_REVISION_MAIL = "SUBSCRIPTION_REVISION_MAIL";
    public static final String EMAIL_TYPE_MANUAL_REGISTRATION_LINK_MAIL = "MANUAL_REGISTRATION_LINK_MAIL";
    public static final String EMAIL_TYPE_DEFAULT_SURVEY_INVITATION_MAIL_BY_CUSTOMER_MAIL = "DEFAULT_SURVEY_INVITATION_MAIL_BY_CUSTOMER_MAIL";
    public static final String EMAIL_TYPE_SURVEY_INVITATION_MAIL_BY_CUSTOMER = "SURVEY_INVITATION_MAIL_BY_CUSTOMER";
    public static final String EMAIL_TYPE_DEFAULT_SURVEY_RESTART_MAIL = "DEFAULT_SURVEY_RESTART_MAIL";
    public static final String EMAIL_TYPE_SOCIAL_CONNECT_MAIL = "SOCIAL_CONNECT_MAIL";
    public static final String EMAIL_TYPE_REPORT_ABUSE_MAIL = "REPORT_ABUSE_MAIL";
    public static final String EMAIL_TYPE_SURVEY_REPORT_MAIL = "SURVEY_REPORT_MAIL";
    public static final String EMAIL_TYPE_CORRUPT_DATA_FROM_CRM_NOTIFICATION_MAIL = "CORRUPT_DATA_FROM_CRM_NOTIFICATION_MAIL";
    public static final String EMAIL_TYPE_INVALID_EMAILS_NOTIFICATION_MAIL = "INVALID_EMAILS_NOTIFICATION_MAIL";
    public static final String EMAIL_TYPE_RECORDS_NOT_UPLOADED_CRM_NOTIFICATION_MAIL = "RECORDS_NOT_UPLOADED_CRM_NOTIFICATION_MAIL";
    public static final String EMAIL_TYPE_HELP_MAIL_TO_ADMIN = "HELP_MAIL_TO_ADMIN";
    public static final String EMAIL_TYPE_ZILLOW_CALL_EXCEEDED_MAIL_TO_ADMIN = "ZILLOW_CALL_EXCEEDED_MAIL_TO_ADMIN";
    public static final String EMAIL_TYPE_REPORT_BUG_MAIL_TO_ADMIN = "REPORT_BUG_MAIL_TO_ADMIN";
    public static final String EMAIL_TYPE_REPORT_BUG_MAIL_TO_ADMIN_FOR_EXCEPTION_IN_BATCH = "REPORT_BUG_MAIL_TO_ADMIN_FOR_EXCEPTION_IN_BATCH";
    public static final String EMAIL_TYPE_COMPLAINT_HANDLE_MAIL = "COMPLAINT_HANDLE_MAIL";
    public static final String EMAIL_TYPE_ZILLOW_REVIEW_COMPLAINT_HANDLE_MAIL = "ZILLOW_REVIEW_COMPLAINT_HANDLE_MAIL";
    public static final String EMAIL_TYPE_FORWARD_CUSTOMER_REPLY_MAIL = "FORWARD_CUSTOMER_REPLY_MAIL";
    public static final String EMAIL_TYPE_BILLING_REPORT_MAIL = "BILLING_REPORT_MAIL";
    public static final String EMAIL_TYPE_CUSTOM_MAIL = "CUSTOM_MAIL";
    public static final String EMAIL_TYPE_CUSTOM_REPORT_MAIL = "CUSTOM_REPORT_MAIL";
    public static final String EMAIL_TYPE_SOCIAL_MEDIA_TOKEN_EXPIRY_EMAIL = "SOCIAL_MEDIA_TOKEN_EXPIRY_EMAIL";
    public static final String EMAIL_TYPE_PAYMENT_FAILED_ALERT_EMAIL = "PAYMENT_FAILED_ALERT_EMAIL";
    public static final String EMAIL_TYPE_CANCEL_SUBSCRIPTION_REQUEST_ALERT_MAIL = "CANCEL_SUBSCRIPTION_REQUEST_ALERT_MAIL";
    public static final String EMAIL_TYPE_WEB_EXCEPTION_EMAIL = "WEB_EXCEPTION_EMAIL";
    public static final String EMAIL_TYPE_NO_TRANSACTION_ALERT_MAIL = "NO_TRANSACTION_ALERT_MAIL";
    public static final String EMAIL_TYPE_HIGH_VOULME_UNPROCESSED_TRANSACTION_ALERT_MAIL = "HIGH_VOULME_UNPROCESSED_TRANSACTION_ALERT_MAIL";
    public static final String EMAIL_TYPE_LESS_VOULME_OF_TRANSACTION_RECEIVED_ALERT_MAIL = "LESS_VOULME_OF_TRANSACTION_RECEIVED_ALERT_MAIL";
    public static final String EMAIL_TYPE_MONTHLY_DIGEST_MAIL = "MONTHLY_DIGEST_MAIL";
    public static final String EMAIL_TYPE_DIGEST_ERROR_MAIL_FOR_COMPANY = "DIGEST_ERROR_MAIL_FOR_COMPANY";
    public static final String EMAIL_TYPE_SURVEY_SOCIALPOST_REMINDER_MAIL = "SURVEY_SOCIALPOST_REMINDER_MAIL";
    public static final String EMAIL_TYPE_SURVEY_COMPLETION_MAIL = "SURVEY_COMPLETION_MAIL";
    public static final String EMAIL_TYPE_SURVEY_COMPLETION_UNPLEASANT_MAIL = "SURVEY_COMPLETION_UNPLEASANT_MAIL";
    public static final String EMAIL_TYPE_PAYMENT_FAILED_ALERT_EMAIL_TO_ADMIN = "PAYMENT_FAILED_ALERT_EMAIL_TO_ADMIN";
    public static final String EMAIL_TYPE_UNSUCCESSFUL_SURVEY_CSV_UPLOAD_MAIL_TO_ADMIN = "UNSUCCESSFUL_SURVEY_CSV_UPLOAD_MAIL_TO_ADMIN";
    public static final String EMAIL_TYPE_UNSUCCESSFUL_SURVEY_CSV_UPLOAD_MAIL_TO_UPLOADER = "UNSUCCESSFUL_SURVEY_CSV_UPLOAD_MAIL_TO_UPLOADER";
    public static final String EMAIL_TYPE_SUCCESSFUL_SURVEY_CSV_UPLOAD_MAIL_TO_UPLOADER = "SUCCESSFUL_SURVEY_CSV_UPLOAD_MAIL_TO_UPLOADER";
    public static final String EMAIL_TYPE_ABUSIVE_HANDLE_MAIL = "ABUSIVE_HANDLE_MAIL";
    public static final String EMAIL_TYPE_FTP_SUCCESSFULLY_PROCESSED_MAIL = "FTP_SUCCESSFULLY_PROCESSED_MAIL";
}
