var phoneFormatList = {
  'AF': '0dd ddd dddd',
  'AL': '0dd ddd ddd',
  'DZ': '0ddd dd dd dd',
  'AS': '(ddd) ddd-dddd',
  'AD': 'dddddddddd',
  'AO': 'ddd ddd ddd',
  'AI': '(ddd) ddd-dddd',
  'AQ': 'dddddddddd',
  'AG': '(ddd) ddd-dddd',
  'AR': 'dddddddddd',
  'AM': '0dd dddddd',
  'AW': 'ddd dddd',
  'AU': '+dd dddd ddd ddd',
  'AT': '0dddd dddddddddd',
  'AZ': 'dddddddddd',
  'BH': 'dddddddddd',
  'BD': 'dddddddddd',
  'BB': 'dddddddddd',
  'BY': 'dddddddddd',
  'BE': 'dddddddddd',
  'BZ': 'dddddddddd',
  'BJ': 'dddddddddd',
  'BM': '(ddd) ddd-dddd',
  'BT': 'dddddddddd',
  'BO': 'dddddddddd',
  'BA': 'dddddddddd',
  'BW': 'dddddddddd',
  'BV': 'dddddddddd',
  'BR': 'dddddddddd',
  'IO': 'dddddddddd',
  'VG': '(ddd) ddd-dddd',
  'BN': 'dddddddddd',
  'BG': 'dddddddddd',
  'BF': 'dddddddddd',
  'BI': 'dddddddddd',
  'CI': 'dddddddddd',
  'KH': 'dddddddddd',
  'CM': 'dddddddddd',
  'CA': '(ddd) ddd-dddd',
  'CV': 'dddddddddd',
  'KY': '(ddd) ddd-dddd',
  'CF': 'dddddddddd',
  'TD': 'dddddddddd',
  'CL': 'dddddddddd',
  'CN': 'dddddddddd',
  'CX': 'dddddddddd',
  'CC': 'dddddddddd',
  'CO': 'dddddddddd',
  'KM': 'dddddddddd',
  'CG': 'dddddddddd',
  'CK': 'dddddddddd',
  'CR': 'dddddddddd',
  'HR': 'dddddddddd',
  'CU': 'dddddddddd',
  'CY': 'dddddddddd',
  'CZ': 'dddddddddd',
  'CD': 'dddddddddd',
  'DK': 'dddddddddd',
  'DJ': 'dddddddddd',
  'DM': '(ddd) ddd-dddd',
  'DO': '(ddd) ddd-dddd',
  'TL': 'dddddddddd',
  'EC': 'dddddddddd',
  'EG': 'dddddddddd',
  'SV': 'dddddddddd',
  'GQ': 'dddddddddd',
  'ER': 'dddddddddd',
  'EE': 'dddddddddd',
  'ET': 'dddddddddd',
  'FO': 'dddddddddd',
  'FK': 'dddddddddd',
  'FJ': 'dddddddddd',
  'FI': 'dddddddddd',
  'MK': 'dddddddddd',
  'FR': 'd dd dd dd dd',
  'GF': 'dddddddddd',
  'PF': 'dddddddddd',
  'TF': 'dddddddddd',
  'GA': 'dddddddddd',
  'GE': 'dddddddddd',
  'DE': 'dddddddddd',
  'GH': 'dddddddddd',
  'GI': 'dddddddddd',
  'GR': 'dddddddddd',
  'GL': 'dddddddddd',
  'GD': '(ddd) ddd-dddd',
  'GP': 'dddddddddd',
  'GU': '(ddd) ddd-dddd',
  'GT': 'dddddddddd',
  'GN': 'dddddddddd',
  'GW': 'dddddddddd',
  'GY': 'dddddddddd',
  'HT': 'dddddddddd',
  'HM': 'dddddddddd',
  'HN': 'dddddddddd',
  'HK': 'dddddddddd',
  'HU': 'dddddddddd',
  'IS': 'dddddddddd',
  'IN': 'dddddddddd',
  'ID': 'dddddddddd',
  'IR': 'dddddddddd',
  'IQ': 'dddddddddd',
  'IE': 'dddddddddd',
  'IL': 'dddddddddd',
  'IT': 'dddddddddd',
  'JM': '(ddd) ddd-dddd',
  'JP': 'dddddddddd',
  'JO': 'dddddddddd',
  'KZ': 'dddddddddd',
  'KE': 'dddddddddd',
  'KI': 'dddddddddd',
  'KW': 'dddddddddd',
  'KG': 'dddddddddd',
  'LA': 'dddddddddd',
  'LV': 'dddddddddd',
  'LB': 'dddddddddd',
  'LS': 'dddddddddd',
  'LR': 'dddddddddd',
  'LY': 'dddddddddd',
  'LI': 'dddddddddd',
  'LT': 'dddddddddd',
  'LU': 'dddddddddd',
  'MO': 'dddddddddd',
  'MG': 'dddddddddd',
  'MW': 'dddddddddd',
  'MY': 'dddddddddd',
  'MV': 'dddddddddd',
  'ML': 'dddddddddd',
  'MT': 'dddddddddd',
  'MH': 'dddddddddd',
  'MQ': 'dddddddddd',
  'MR': 'dddddddddd',
  'MU': 'dddddddddd',
  'YT': 'dddddddddd',
  'MX': 'dddddddddd',
  'FM': 'dddddddddd',
  'MD': 'dddddddddd',
  'MC': 'dddddddddd',
  'MN': 'dddddddddd',
  'MS': '(ddd) ddd-dddd',
  'MA': 'dddddddddd',
  'MZ': 'dddddddddd',
  'MM': 'dddddddddd',
  'NA': 'dddddddddd',
  'NR': 'dddddddddd',
  'NP': 'dddddddddd',
  'NL': 'dddddddddd',
  'AN': 'dddddddddd',
  'NC': 'dddddddddd',
  'NZ': 'dddddddddd',
  'NI': 'dddddddddd',
  'NE': 'dddddddddd',
  'NG': 'dddddddddd',
  'NU': 'dddddddddd',
  'NF': 'dddddddddd',
  'KP': 'dddddddddd',
  'MP': '(ddd) ddd-dddd',
  'NO': 'dddddddddd',
  'OM': 'dddddddddd',
  'PK': 'dddddddddd',
  'PW': 'dddddddddd',
  'PA': 'dddddddddd',
  'PG': 'dddddddddd',
  'PY': 'dddddddddd',
  'PE': 'dddddddddd',
  'PH': 'dddddddddd',
  'PN': 'dddddddddd',
  'PL': 'dddddddddd',
  'PT': 'dddddddddd',
  'PR': '(ddd) ddd-dddd',
  'QA': 'dddddddddd',
  'RE': 'dddddddddd',
  'RO': 'dddddddddd',
  'RU': 'dddddddddd',
  'RW': 'dddddddddd',
  'ST': 'dddddddddd',
  'SH': 'dddddddddd',
  'KN': '(ddd) ddd-dddd',
  'LC': '(ddd) ddd-dddd',
  'PM': 'dddddddddd',
  'VC': '(ddd) ddd-dddd',
  'WS': 'dddddddddd',
  'SM': 'dddddddddd',
  'SA': 'dddddddddd',
  'SN': 'dddddddddd',
  'SC': 'dddddddddd',
  'SL': 'dddddddddd',
  'SG': 'dddddddddd',
  'SK': 'dddddddddd',
  'SI': 'dddddddddd',
  'SB': 'dddddddddd',
  'SO': 'dddddddddd',
  'ZA': 'dddddddddd',
  'GS': 'dddddddddd',
  'KR': 'dddddddddd',
  'ES': 'dddddddddd',
  'LK': 'dddddddddd',
  'SD': 'dddddddddd',
  'SR': 'dddddddddd',
  'SJ': 'dddddddddd',
  'SZ': 'dddddddddd',
  'SE': 'dddddddddd',
  'CH': 'dddddddddd',
  'SY': 'dddddddddd',
  'TW': 'dddddddddd',
  'TJ': 'dddddddddd',
  'TZ': 'dddddddddd',
  'TH': 'dddddddddd',
  'BS': '(ddd) ddd-dddd',
  'GM': 'dddddddddd',
  'TG': 'dddddddddd',
  'TK': 'dddddddddd',
  'TO': 'dddddddddd',
  'TT': '(ddd) ddd-dddd',
  'TN': 'dddddddddd',
  'TR': 'dddddddddd',
  'TM': 'dddddddddd',
  'TC': '(ddd) ddd-dddd',
  'TV': 'dddddddddd',
  'VI': '(ddd) ddd-dddd',
  'UG': 'dddddddddd',
  'UA': 'dddddddddd',
  'AE': 'dddddddddd',
  'GB': '(ddd) dddd dddd',
  'US': '(ddd) ddd-dddd',
  'UM': 'dddddddddd',
  'UY': 'dddddddddd',
  'UZ': 'dddddddddd',
  'VU': 'dddddddddd',
  'VA': 'dddddddddd',
  'VE': 'dddddddddd',
  'VN': 'dddddddddd',
  'WF': 'dddddddddd',
  'EH': 'dddddddddd',
  'YE': 'dddddddddd',
  'YU': 'dddddddddd',
  'ZM': 'dddddddddd',
  'ZW': 'dddddddddd'
};