USE `ss_user`;

CREATE TABLE IF NOT EXISTS `ss_user`.`FEED_STATUS` (
	`FEED_STATUS_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`COMPANY_ID` INT UNSIGNED,
	`REGION_ID` INT UNSIGNED,
	`BRANCH_ID` INT UNSIGNED,
	`AGENT_ID` INT UNSIGNED,
	`FEED_SOURCE` VARCHAR(250) NOT NULL COMMENT 'Source of feed',
	`LAST_FETCHED_POST_ID` VARCHAR(500) NOT NULL,
	`LAST_FETCHED_TILL` TIMESTAMP,
    `RETRIES` INT,
	`REMINDER_SENT_ON` TIMESTAMP,
	PRIMARY KEY (`FEED_STATUS_ID`))
ENGINE = InnoDB
COMMENT = 'Holds the Social Feed Status meta data';
