use ss_user;

ALTER TABLE COMPANY ADD COLUMN BILLING_MODE VARCHAR(1) NOT NULL DEFAULT 'A' AFTER STATUS;

CREATE TABLE IF NOT EXISTS `ss_user`.`USER_API_KEYS` (
	USER_API_KEY_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	USER_NAME VARCHAR(250) NOT NULL,
	USER_EMAIL_ADDRESS VARCHAR(250) NOT NULL,
	API_KEY VARCHAR(512) NOT NULL,
	STATUS INT(1) NOT NULL,
	CREATED_ON TIMESTAMP NOT NULL,
	MODIFIED_ON TIMESTAMP NOT NULL,
	PRIMARY KEY (USER_API_KEY_ID)
)
ENGINE = InnoDB
COMMENT = 'Holds user api keys';