use ss_user;

CREATE TABLE IF NOT EXISTS `ss_user`.`SURVEY_PRE_INITIATION` (
	SURVEY_PRE_INITIATION_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	SURVEY_SOURCE VARCHAR(100) NOT NULL,
	SURVEY_SOURCE_ID VARCHAR(250) NULL,
	COMPANY_ID INT UNSIGNED NOT NULL,
	AGENT_ID INT UNSIGNED NOT NULL,
	CUSTOMER_FIRST_NAME VARCHAR(100) NOT NULL,
	CUSTOMER_LAST_NAME VARCHAR(100) NULL,
	CUSTOMER_EMAIL_ID VARCHAR(250) NOT NULL,
	CUSTOMER_INTERACTION_DETAILS VARCHAR(500) NULL,
	ENGAGEMENT_CLOSED_TIME TIMESTAMP NOT NULL,
	REMINDER_COUNTS INT NOT NULL,
	LAST_REMINDER_TIME TIMESTAMP NOT NULL,
	STATUS INT(1) NOT NULL,
	CREATED_ON TIMESTAMP NOT NULL,
	MODIFIED_ON TIMESTAMP NOT NULL,
	PRIMARY KEY (SURVEY_PRE_INITIATION_ID)
)
ENGINE = InnoDB
COMMENT = 'Holds survey pre-initiation details';

DROP TABLE `ss_user`.`SURVEY_PRE_INITIATION`;

CREATE TABLE IF NOT EXISTS `ss_user`.`SURVEY_PRE_INITIATION` (
  SURVEY_PRE_INITIATION_ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  SURVEY_SOURCE VARCHAR(100) NOT NULL,
  SURVEY_SOURCE_ID VARCHAR(250) DEFAULT NULL,
  COMPANY_ID INT(10) UNSIGNED NOT NULL,
  AGENT_ID CHAR(36) NOT NULL,
  AGENT_NAME VARCHAR(50) DEFAULT NULL,
  AGENT_EMAILID VARCHAR(255) DEFAULT NULL,
  CUSTOMER_FIRST_NAME VARCHAR(100) NOT NULL,
  CUSTOMER_LAST_NAME VARCHAR(100) DEFAULT NULL,
  CUSTOMER_EMAIL_ID VARCHAR(250) NOT NULL,
  CUSTOMER_INTERACTION_DETAILS VARCHAR(500) DEFAULT NULL,
  ENGAGEMENT_CLOSED_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  REMINDER_COUNTS INT(11) NOT NULL,
  LAST_REMINDER_TIME TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  STATUS INT(1) NOT NULL,
  CREATED_ON TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  MODIFIED_ON TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (SURVEY_PRE_INITIATION_ID)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET latin1
COLLATE latin1_swedish_ci
COMMENT = 'Holds survey pre-initiation details';