use ss_user;

CREATE TABLE IF NOT EXISTS `ss_user`.`SURVEY_PRE_INITIATION` (
	SURVEY_PRE_INITIATION_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	SURVEY_SOURCE VARCHAR(100) NOT NULL,
	SURVEY_SOURCE_ID VARCHAR(250) NULL,
	COMPANY_ID INT UNSIGNED NOT NULL,
	AGENT_ID INT UNSIGNED NOT NULL,
	CUSTOMER_FIRST_NAME VARCHAR(100) NOT NULL,
	CUSTOMER_LAST_NAME VARCHAR(100) NULL,
	CUSTOMER_EMAIL_ID VARCHAR(250) NOT NULL,
	CUSTOMER_INTERACTION_DETAILS VARCHAR(500) NULL,
	ENGAGEMENT_CLOSED_TIME TIMESTAMP NOT NULL,
	REMINDER_COUNTS INT NOT NULL,
	LAST_REMINDER_TIME TIMESTAMP NOT NULL,
	STATUS INT(1) NOT NULL,
	CREATED_ON TIMESTAMP NOT NULL,
	MODIFIED_ON TIMESTAMP NOT NULL,
	PRIMARY KEY (SURVEY_PRE_INITIATION_ID)
)
ENGINE = InnoDB
COMMENT = 'Holds survey pre-initiation details';