USE `ss_user`;

ALTER TABLE `ss_user`.`SURVEY` DROP FOREIGN KEY `fk_SURVEY_VERTICALS_MASTER1`;
DROP INDEX `fk_SURVEY_VERTICALS_MASTER1_idx` on `ss_user`.`SURVEY`;
ALTER TABLE `ss_user`.`SURVEY` DROP COLUMN `VERTICAL_ID`;

-- -----------------------------------------------------
-- Table `ss_user`.`SURVEY_VERTICAL_MAPPING`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ss_user`.`SURVEY_VERTICAL_MAPPING` (
	`SURVEY_VERTICAL_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `SURVEY_ID` INT UNSIGNED NOT NULL,
	`VERTICAL_ID` INT NOT NULL,
	`STATUS` INT(1) NOT NULL,
	`CREATED_ON` TIMESTAMP NOT NULL,
	`CREATED_BY` VARCHAR(45) NOT NULL,
	`MODIFIED_ON` TIMESTAMP NOT NULL,
	`MODIFIED_BY` VARCHAR(45) NOT NULL,
	PRIMARY KEY (`SURVEY_VERTICAL_ID`),
	INDEX `fk_SURVEY_VERTICAL_MAPPING_VERTICAL1_idx` (`VERTICAL_ID` ASC),
	INDEX `fk_SURVEY_VERTICAL_MAPPING_SURVEY1_idx` (`SURVEY_ID` ASC),
	CONSTRAINT `fk_SURVEY_VERTICAL_MAPPING_VERTICAL1`
		FOREIGN KEY (`VERTICAL_ID`)
		REFERENCES `ss_user`.`VERTICALS_MASTER` (`VERTICALS_MASTER_ID`)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION,
	CONSTRAINT `fk_SURVEY_VERTICAL_MAPPING_SURVEY1`
		FOREIGN KEY (`SURVEY_ID`)
		REFERENCES `ss_user`.`SURVEY` (`SURVEY_ID`)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION)
ENGINE = InnoDB;


