UPDATE `ss_user`.`VERTICALS_MASTER` SET `VERTICAL_NAME`='CONSTRUCTION' WHERE `VERTICALS_MASTER_ID`='17';
UPDATE `ss_user`.`VERTICALS_MASTER` SET `VERTICAL_NAME`='RELIGIOUS INSTITUTIONS' WHERE `VERTICALS_MASTER_ID`='96';
UPDATE `ss_user`.`verticals_master` SET `VERTICAL_NAME`='PAPER & FOREST PRODUCTS' WHERE `VERTICALS_MASTER_ID`='81';
UPDATE `ss_user`.`verticals_master` SET `VERTICAL_NAME`='TRANSLATION AND LOCALIZATION' WHERE `VERTICALS_MASTER_ID`='107';

