UPDATE `ss_user`.`verticals_master` SET `VERTICAL_NAME`='CONSTRUCTION' WHERE `VERTICALS_MASTER_ID`='17';
UPDATE `ss_user`.`verticals_master` SET `VERTICAL_NAME`='RELIGIOUS INSTITUTIONS' WHERE `VERTICALS_MASTER_ID`='96';
