INSERT INTO `ss_user`.`VERTICAL_CRM_MAPPING` (`VERTICAL_CRM_MAPPING_ID`, `VERTICAL_ID`, `CRM_ID`, `STATUS`, `CREATED_ON`, `CREATED_BY`, `MODIFIED_ON`, `MODIFIED_BY`) VALUES ('-1', '-1', '1', '1', now(), '1', now(), '1');

UPDATE `ss_user`.`CRM_MASTER` SET `CRM_NAME`='Encompass' WHERE `CRM_MASTER_ID`='1';