#INSERT INTO `ss_user`.`COMPANY` (`COMPANY_ID`, `COMPANY`, `VERTICAL_ID`, `REGISTRATION_STAGE`, `IS_REGISTRATION_COMPLETE`, `STATUS`, `BILLING_MODE`, `CREATED_ON`, `CREATED_BY`, `MODIFIED_ON`, `MODIFIED_BY`) VALUES (0, 'Admin Company', -1, null, 1, 1, 'A', now(), 1, now(), 1);

ALTER TABLE `ss_user`.`USERS` ADD COLUMN `SUPER_ADMIN` INT(1) NULL AFTER `NUM_OF_LOGINS`;

ALTER TABLE `ss_user`.`users` 
CHANGE COLUMN `SUPER_ADMIN` `SUPER_ADMIN` INT(1) NULL DEFAULT 0 ;

UPDATE `ss_user`.`users` SET `SUPER_ADMIN`='0' WHERE `USER_ID`>0;


INSERT INTO `ss_user`.`USERS` (`USER_ID`, `COMPANY_ID`, `LOGIN_NAME`, `LOGIN_PASSWORD`, `EMAIL_ID`, `FIRST_NAME`, `LAST_NAME`, `SOURCE`, `SOURCE_USER_ID`, `IS_ATLEAST_ONE_USERPROFILE_COMPLETE`, `IS_OWNER`, `STATUS`, `NUM_OF_LOGINS`,`SUPER_ADMIN` , `CREATED_ON`, `CREATED_BY`, `MODIFIED_ON`, `MODIFIED_BY`) VALUES (0, 1, 'admin@socialsurvey.me', '3f08b178cf44b2ba1745bd72cf6c7db6f5097385511e85ca9f210f12376ea0a43bc8323b0ec4a6b92c5ab3912bb7cc1b4b043ac811f664ba4af7f3c51974935c', 'admin@socialsurvey.me', 'admin', 'realtech', 'AP', 0, 1, 1, 1, 0, 1,now(), 'ADMIN', now(), 'ADMIN');