use ss_user;

CREATE TABLE IF NOT EXISTS `FILE_UPLOAD`(
	`FILE_UPLOAD_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`COMPANY_ID` INT UNSIGNED NOT NULL,
	`ADMIN_USER_ID` INT NOT NULL,
	`FILE_NAME` VARCHAR(250) NOT NULL,
	`UPLOAD_TYPE` INT(1) NOT NULL,
	`STATUS` INT(1) NOT NULL,
	`CREATED_ON` TIMESTAMP NOT NULL,
	`MODIFIED_ON` TIMESTAMP NOT NULL,
	CONSTRAINT `fk_FILE_UPLOAD_COMPANY1`
    FOREIGN KEY (`COMPANY_ID`)
    REFERENCES `ss_user`.`COMPANY` (`COMPANY_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);

ALTER TABLE `ss_user`.`USERS` MODIFY COLUMN `LOGIN_NAME` VARCHAR(100) NOT NULL;