ALTER TABLE ss_user.`USER_PROFILE` ADD COLUMN `IS_PRIMARY` INT(1) NOT NULL DEFAULT 0 AFTER `IS_PROFILE_COMPLETE`;

ALTER TABLE ss_user.`COMPANY` ADD COLUMN `SETTINGS_LOCK_STATUS` VARCHAR(50) NOT NULL DEFAULT '0' AFTER `BILLING_MODE`;
ALTER TABLE ss_user.`COMPANY` ADD COLUMN `SETTINGS_SET_STATUS` VARCHAR(50) NOT NULL DEFAULT '0' AFTER `SETTINGS_LOCK_STATUS`;

ALTER TABLE ss_user.`REGION` ADD COLUMN `SETTINGS_LOCK_STATUS` VARCHAR(50) NOT NULL DEFAULT '0' AFTER `IS_DEFAULT_BY_SYSTEM`;
ALTER TABLE ss_user.`REGION` ADD COLUMN `SETTINGS_SET_STATUS` VARCHAR(50) NOT NULL DEFAULT '0' AFTER `SETTINGS_LOCK_STATUS`;

ALTER TABLE ss_user.`BRANCH` ADD COLUMN `SETTINGS_LOCK_STATUS` VARCHAR(50) NOT NULL DEFAULT '0' AFTER `IS_DEFAULT_BY_SYSTEM`;
ALTER TABLE ss_user.`BRANCH` ADD COLUMN `SETTINGS_SET_STATUS` VARCHAR(50) NOT NULL DEFAULT '0' AFTER `SETTINGS_LOCK_STATUS`;