INSERT INTO ss_user.`CRM_MASTER` (CRM_MASTER_ID, CRM_NAME, STATUS, CREATED_ON, CREATED_BY, MODIFIED_ON, MODIFIED_BY) VALUES (2,'Dotloop', 1, NOW(), 1, NOW(), 1);

INSERT INTO `ss_user`.`VERTICAL_CRM_MAPPING` (`VERTICAL_CRM_MAPPING_ID`, `VERTICAL_ID`, `CRM_ID`, `STATUS`, `CREATED_ON`, `CREATED_BY`, `MODIFIED_ON`, `MODIFIED_BY`) VALUES ('0','-1', '2', '1', NOW(), '1', NOW(), '1');
