ALTER TABLE `ss_user`.`SURVEY_PRE_INITIATION` 
   ADD COLUMN `REGION_COLLECTION_ID` int(11) NULL AFTER `MODIFIED_ON`, 
   ADD COLUMN `BRANCH_COLLECTION_ID` int(11) NULL AFTER `REGION_COLLECTION_ID`, 
   ADD COLUMN `AGENT_COLLECTION_ID` int(11) NULL AFTER `BRANCH_COLLECTION_ID`;
   
   
   
   
ALTER TABLE `ss_user`.`SURVEY_PRE_INITIATION` 
   ADD COLUMN `COLLECTION_NAME` varchar(200) NULL AFTER `AGENT_COLLECTION_ID`;
   
   
   
   
   