ALTER TABLE `ss_user`.`COMPANY_DOTLOOP_PROFILEMAPPING` 
   ADD COLUMN `REGION_ID` bigint(11) NULL AFTER `PROFILE_ACTIVE`, 
   ADD COLUMN `BRANCH_ID` bigint(11) NULL AFTER `REGION_ID`, 
   ADD COLUMN `AGENT_ID` bigint(11) NULL AFTER `BRANCH_ID`;
   
 
   
RENAME TABLE COMPANY_DOTLOOP_PROFILEMAPPING TO COLLECTION_DOTLOOP_PROFILEMAPPING;


  
ALTER TABLE `ss_user`.`COLLECTION_DOTLOOP_PROFILEMAPPING` 
   CHANGE `COMPANY_PROFILE_MAPPING_ID` `COLLECTION_PROFILE_MAPPING_ID` bigint(11) NOT NULL AUTO_INCREMENT;
   
   