RENAME TABLE `ss_user`.`COMPANY_DOTLOOP_PROFILEMAPPING` TO `ss_user`.`COLLECTION_DOTLOOP_PROFILEMAPPING`;

ALTER TABLE `ss_user`.`COLLECTION_DOTLOOP_PROFILEMAPPING` 
   ADD COLUMN `REGION_ID` bigint(11) NULL AFTER `PROFILE_ACTIVE`, 
   ADD COLUMN `BRANCH_ID` bigint(11) NULL AFTER `REGION_ID`, 
   ADD COLUMN `AGENT_ID` bigint(11) NULL AFTER `BRANCH_ID`;
   

  
ALTER TABLE `ss_user`.`COLLECTION_DOTLOOP_PROFILEMAPPING` 
   CHANGE `COMPANY_PROFILE_MAPPING_ID` `COLLECTION_PROFILE_MAPPING_ID` bigint(11) NOT NULL AUTO_INCREMENT;
   
ALTER TABLE `ss_user`.`COLLECTION_DOTLOOP_PROFILEMAPPING` 
   CHANGE `COMPANY_ID` `COMPANY_ID` bigint(11) DEFAULT '-1' NOT NULL , 
   CHANGE `REGION_ID` `REGION_ID` bigint(11) DEFAULT '-1' NOT NULL , 
   CHANGE `BRANCH_ID` `BRANCH_ID` bigint(11) DEFAULT '-1' NOT NULL , 
   CHANGE `AGENT_ID` `AGENT_ID` bigint(11) DEFAULT '-1' NOT NULL ;
   
ALTER TABLE `ss_user`.`SURVEY_PRE_INITIATION` 
   CHANGE `REGION_COLLECTION_ID` `REGION_COLLECTION_ID` int(11) DEFAULT '-1' NOT NULL , 
   CHANGE `BRANCH_COLLECTION_ID` `BRANCH_COLLECTION_ID` int(11) DEFAULT '-1' NOT NULL , 
   CHANGE `AGENT_COLLECTION_ID` `AGENT_COLLECTION_ID` int(11) DEFAULT '-1' NOT NULL ;
   
   
   ALTER TABLE `ss_user`.`SURVEY_PRE_INITIATION` DROP COLUMN `AGENT_COLLECTION_ID`;
   
   
  
   