ALTER TABLE `ss_user`.`EMAIL_ENTITY` 
   ADD COLUMN `CREATED_BY` varchar(255) NULL AFTER `EMAIL_OBJECT`, 
   ADD COLUMN `CREATED_ON` timestamp NULL AFTER `CREATED_BY`, 
   ADD COLUMN `MODIFIED_BY` varchar(255) NULL AFTER `CREATED_ON`, 
   ADD COLUMN `MODIFIED_ON` timestamp NULL AFTER `MODIFIED_BY`
   
   
 

UPDATE `ss_user`.`EMAIL_ENTITY` SET CREATED_ON = NOW() WHERE CREATED_ON IS NULL;
UPDATE `ss_user`.`EMAIL_ENTITY` SET MODIFIED_ON = NOW() WHERE MODIFIED_ON IS NULL;
UPDATE `ss_user`.`EMAIL_ENTITY` SET CREATED_BY = "Admin" WHERE CREATED_BY IS NULL;
UPDATE `ss_user`.`EMAIL_ENTITY` SET MODIFIED_BY = "Admin" WHERE MODIFIED_BY IS NULL;