ALTER TABLE `ss_user`.`DOTLOOP_PROFILE_LOOP_MAPPING` 
   ADD COLUMN `COMPANY_ID` BIGINT(11) NULL AFTER `LOOP_CLOSED_TIME`, 
   ADD COLUMN `REGION_ID` BIGINT(11) NULL AFTER `COMPANY_ID`, 
   ADD COLUMN `BRANCH_ID` BIGINT(11) NULL AFTER `REGION_ID`, 
   ADD COLUMN `AGENT_ID` BIGINT(11) NULL AFTER `BRANCH_ID`,
   ADD COLUMN `COLLECTION_NAME` VARCHAR(100) NULL AFTER `AGENT_ID`;