ALTER TABLE ss_user.BATCH_TRACKER
ADD COLUMN `BATCH_NAME` text NOT NULL AFTER `BATCH_TYPE`,
ADD COLUMN `LAST_START_TIME` timestamp NOT NULL DEFAULT '1970-01-01 18:30:00' AFTER `BATCH_NAME`,
CHANGE COLUMN `LAST_RUN_TIME` `LAST_END_TIME` timestamp NOT NULL DEFAULT '1970-01-01 18:30:00',
ADD COLUMN `ERROR` text AFTER `MODIFIED_BY`,
ADD COLUMN `DESCRIPTION` text AFTER `ERROR`;



UPDATE ss_user.BATCH_TRACKER SET BATCH_NAME="Agent's review count in solr updater"  WHERE BATCH_TYPE='reviewCountUpdater';
UPDATE ss_user.BATCH_TRACKER SET BATCH_NAME="Social Post Import In Sol"  WHERE BATCH_TYPE='socialMonitorLastBuildTime';
