ALTER TABLE ss_user.CRM_BATCH_TRACKER
ADD COLUMN `REGION_ID` INT(11) after `COMPANY_ID`,
ADD COLUMN `BRANCH_ID` INT(11) after `REGION_ID`,
ADD COLUMN `RECENT_RECORD_FETCHED_START_DATE` timestamp NOT NULL DEFAULT '1970-01-01 18:30:00' AFTER `SOURCE`,
CHANGE COLUMN `RECENT_RECORD_FETCHED_DATE` `RECENT_RECORD_FETCHED_END_DATE` timestamp NOT NULL DEFAULT '1970-01-01 18:30:00',
ADD COLUMN `ERROR` text AFTER `MODIFIED_ON`,
ADD COLUMN `DESCRIPTION` text AFTER `ERROR`;
