CREATE TABLE `ss_user`.`USER_EMAIL_MAPPING` (
  `USER_EMAIL_MAPPING_ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `USER_ID` INT(10) UNSIGNED NOT NULL,
  `EMAIL_ID` VARCHAR(250) NOT NULL,
  `STATUS` INT(1) NOT NULL,
  `CREATED_ON` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `CREATED_BY` VARCHAR(45) NOT NULL,
  `MODIFIED_ON` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  `MODIFIED_BY` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`USER_EMAIL_MAPPING_ID`),
  INDEX `fk_USER_EMAIL_MAPPING_USER1_idx` (`USER_ID` ASC) ,
  CONSTRAINT `fk_USER_EMAIL_MAPPING_USER1`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `ss_user`.`USERS` (`USER_ID`)
);
