ALTER TABLE ss_user.LICENSE_DETAILS
ADD COLUMN `INVOICE_CYCLE_DATE` INT(4) DEFAULT NULL after `SUBSCRIPTION_ID_SOURCE` ,
ADD COLUMN `INVOICE_CYCLE_PERIOD_MONTH` INT(4) DEFAULT NULL after `INVOICE_CYCLE_DATE`,
ADD COLUMN `NEXT_INVOICE_BILLING_DATE` TIMESTAMP NULL after `INVOICE_CYCLE_PERIOD_MONTH`,
ADD COLUMN `RECIPIENT_MAIL_ID` VARCHAR(255) DEFAULT NULL after `NEXT_INVOICE_BILLING_DATE`;
