CREATE TABLE ss_user.ZILLOW_TEMP_POST(
	ID INT(11) NOT NULL AUTO_INCREMENT,
	ENTITY_COLUMN_NAME VARCHAR(50) NOT NULL,
	ENTITY_ID INT(11) NOT NULL,
	ZILLOW_REVIEW_URL VARCHAR(100) NOT NULL,
	ZILLOW_REVIEW_SOURCE_LINK VARCHAR(100) NOT NULL,
	ZILLOW_REVIEW_RATING DOUBLE PRECISION DEFAULT 0 NOT NULL,
	ZILLOW_REVIEWER_NAME VARCHAR(50) NOT NULL,
	ZILLOW_REVIEW_SUMMARY VARCHAR(200) NOT NULL,
	ZILLOW_REVIEW_DESCRIPTION VARCHAR(2000) NOT NULL,
	ZILLOW_REVIEW_DATE TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
	ZILLOW_SURVEY_ID VARCHAR(30) NOT NULL,
	CREATED_ON TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CREATED_BY VARCHAR(45) NOT NULL,
	MODIFIED_ON TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
	MODIFIED_BY VARCHAR(45) NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE ss_user.EXTERNAL_SURVEY_TRACKER(
	ID INT(11) NOT NULL AUTO_INCREMENT,
	ENTITY_COLUMN_NAME VARCHAR(50) NOT NULL,
	ENTITY_ID INT(11) NOT NULL,
	REVIEW_SOURCE VARCHAR(50) NOT NULL,
	REVIEW_SOURCE_LINK VARCHAR(500) NOT NULL,
	REVIEW_RATING DOUBLE PRECISION DEFAULT 0 NOT NULL,
	REVIEW_SOURCE_URL VARCHAR(500) NOT NULL,
	COMPLAINT_RES_STATUS INT(1) DEFAULT 0 NOT NULL,
	REVIEW_DATE TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
	CREATED_ON TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CREATED_BY VARCHAR(45) NOT NULL,
	MODIFIED_ON TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
	MODIFIED_BY VARCHAR(45) NOT NULL,
	PRIMARY KEY (ID)
);
