ALTER TABLE `ss_user`.`USER_EMAIL_MAPPING` 
ADD COLUMN `COMPANY_ID` INT(10) UNSIGNED NOT NULL AFTER `USER_ID`;
ALTER TABLE `ss_user`.`USER_EMAIL_MAPPING` 
ADD CONSTRAINT `fk_USER_EMAIL_MAPPING_1`
FOREIGN KEY (`COMPANY_ID`) REFERENCES `ss_user`.`COMPANY` (`COMPANY_ID`)
ON DELETE NO ACTION ON UPDATE NO ACTION;
