DROP TABLE IF EXISTS `COMPANY_IGNORED_EMAIL_MAPPING`;
CREATE TABLE `COMPANY_IGNORED_EMAIL_MAPPING` (
  `COMPANY_IGNORED_EMAIL_MAPPING_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `EMAIL_ID` varchar(255) NOT NULL,
  `COMPANY_ID` int(10) unsigned NOT NULL,
  `CREATED_ON` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `CREATED_BY` varchar(45) DEFAULT NULL,
  `MODIFIED_ON` timestamp NULL DEFAULT '0000-00-00 00:00:00',
  `MODIFIED_BY` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`COMPANY_IGNORED_EMAIL_MAPPING_ID`),
  KEY `fk_COMPANY_IGNORED_EMAIL_MAPPING_1_idx` (`COMPANY_ID`),
  CONSTRAINT `fk_COMPANY_IGNORED_EMAIL_MAPPING_1` FOREIGN KEY (`COMPANY_ID`) REFERENCES `COMPANY` (`COMPANY_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;
