CREATE TABLE IF NOT EXISTS ss_user.REFERRAL_INVITATION (
	REFERRAL_INVITATION_ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	REFERRAL_ID VARCHAR(250) NOT NULL,
	REFERRAL_NAME VARCHAR(250),
	REFERRAL_DESCRIPTION VARCHAR(500),
	STATUS INT(1) NOT NULL,
	CREATED_ON TIMESTAMP NOT NULL,
	CREATED_BY VARCHAR(50) NOT NULL,
	MODIFIED_ON TIMESTAMP NOT NULL,
	MODIFIED_BY VARCHAR(50),
	UNIQUE (REFERRAL_ID)
);

CREATE TABLE IF NOT EXISTS ss_user.USER_REFERRAL_MAPPING (
	USER_REFERRAL_MAPPING_ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	REFERRAL_INVITATION_ID INT UNSIGNED NOT NULL,
	USER_ID INT UNSIGNED NOT NULL,
	STATUS INT(1) NOT NULL,
	CREATED_ON TIMESTAMP NOT NULL,
	CREATED_BY VARCHAR(50) NOT NULL,
	MODIFIED_ON TIMESTAMP NOT NULL,
	MODIFIED_BY VARCHAR(50),
	CONSTRAINT `fk_ss_user.USER_REFERRAL_MAPPING_REFERRAL_INVITATION`
    FOREIGN KEY (`REFERRAL_INVITATION_ID`)
    REFERENCES `ss_user`.`REFERRAL_INVITATION` (`REFERRAL_INVITATION_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
	CONSTRAINT `fk_ss_user.USER_REFERRAL_MAPPING_USERS`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `ss_user`.`USERS` (`USER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);


