CREATE TABLE IF NOT EXISTS ss_user.REFERRAL_INVITATION (
	REFERRAL_INVITATION_ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	REFERRAL_ID VARCHAR(250) NOT NULL,
	REFERRAL_NAME VARCHAR(250),
	REFERRAL_DESCRIPTION VARCHAR(500),
	STATUS INT(1) NOT NULL,
	CREATED_ON TIMESTAMP NOT NULL,
	CREATED_BY VARCHAR(50) NOT NULL,
	MODIFIED_ON TIMESTAMP NOT NULL,
	MODIFIED_BY VARCHAR(50),
	UNIQUE (REFERRAL_ID)
);
