CREATE TABLE `ss_user`.`EVENT` (
  `AGENT_ID` INT NOT NULL DEFAULT 0,
  `REGION_ID` INT NOT NULL DEFAULT 0,
  `BRANCH_ID` INT NOT NULL DEFAULT 0,
  `COMPANY_ID` INT NOT NULL,
  `EVENT_TYPE` VARCHAR(45) NOT NULL,
  `ACTION` VARCHAR(45) NOT NULL,
  `MODIFIED_ON` TIMESTAMP NOT NULL,
  `MODIFIED_BY` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`COMPANY_ID`, `MODIFIED_ON`));

