ALTER TABLE `SS_USER`.`VERTICALS_MASTER` 
ADD COLUMN `PRIORITY_ORDER` INT NOT NULL DEFAULT 0 AFTER `MODIFIED_BY`;

ALTER TABLE `SS_USER`.`USERS` 
ADD COLUMN `REGISTRATION_STAGE` VARCHAR(45) DEFAULT "NOT_STARTED",
ADD COLUMN `FORCE_PASSWORD` INT NOT NULL DEFAULT 0 ;



