ALTER TABLE `ss_user`.`SURVEY_PRE_INITIATION` 
ADD COLUMN `STATE` VARCHAR(100) NULL DEFAULT NULL COMMENT '' AFTER `ERROR_CODE`,
ADD COLUMN `CITY` VARCHAR(100) NULL DEFAULT NULL COMMENT '' AFTER `STATE`;
