use ss_user;

CREATE TABLE IF NOT EXISTS `UPLOAD_STATUS`(
	`UPLOAD_STATUS_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`COMPANY_ID` INT UNSIGNED NOT NULL,
	`MESSAGE` VARCHAR(500) NOT NULL,
	`STATUS` INT(1) NOT NULL,
	`CREATED_ON` TIMESTAMP NOT NULL,
	`MODIFIED_ON` TIMESTAMP NOT NULL,
	CONSTRAINT `fk_UPLOAD_STATUS_COMPANY1`
    FOREIGN KEY (`COMPANY_ID`)
    REFERENCES `ss_user`.`COMPANY` (`COMPANY_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);

ALTER TABLE `ss_user`.`UPLOAD_STATUS` 
ADD COLUMN `ADMIN_USER_ID` INT(11) NOT NULL COMMENT '' AFTER `COMPANY_ID`;

