use ss_user;
ALTER TABLE ss_user.ACCOUNTS_MASTER ADD COLUMN MIN_USERS_ALLOWED INT(11) NOT NULL DEFAULT -1 AFTER `MAX_USERS_ALLOWED`;
UPDATE ss_user.ACCOUNTS_MASTER SET `MIN_USERS_ALLOWED` = 5 WHERE `ACCOUNTS_MASTER_ID` = 4;

delete from ss_user.ACCOUNTS_MASTER where ACCOUNTS_MASTER_ID not in (1,4);

update ss_user.ACCOUNTS_MASTER set AMOUNT = 39.95 where ACCOUNTS_MASTER_ID = 1;
update ss_user.ACCOUNTS_MASTER set AMOUNT = 29.95 where ACCOUNTS_MASTER_ID = 4;