use ss_user;
ALTER TABLE ss_user.accounts_master ADD COLUMN MIN_USERS_ALLOWED INT(11) NOT NULL DEFAULT -1 AFTER `MAX_USERS_ALLOWED`;
UPDATE ss_user.accounts_master SET `MIN_USERS_ALLOWED` = 5 WHERE `ACCOUNTS_MASTER_ID` = 4;