use ss_user;
-- -----------------------------------------------------
-- Table `ss_user`.`VENDASTA_SSO_TICKET`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ss_user`.`VENDASTA_SSO_TICKET` (
  `VENDASTA_SSO_TICKET_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `VENDASTA_SSO_TICKET` VARCHAR(32) NOT NULL,
  `PRODUCT_ID` VARCHAR(2) NOT NULL,
  `VENDASTA_SSO_TOKEN` VARCHAR(32) NOT NULL,
  `STATUS` TINYINT NOT NULL,
  `CREATED_ON` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `MODIFIED_ON` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATED_BY` VARCHAR(20) NOT NULL,
  `MODIFIED_BY` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`VENDASTA_SSO_TICKET_ID`)
  )
ENGINE = InnoDB
COMMENT = 'vendasta single use short lived ticket' ;