ALTER TABLE `ss_user`.`FILE_UPLOAD`   
  ADD COLUMN `START_DATE` TIMESTAMP NULL AFTER `MODIFIED_ON`,
  ADD COLUMN `END_DATE` TIMESTAMP NULL AFTER `START_DATE`;
  ADD COLUMN `PROFILE_LEVEL` VARCHAR(50) NULL AFTER `END_DATE`,
  ADD COLUMN `PROFILE_VALUE` INT(10) NULL AFTER `PROFILE_LEVEL`;
