ALTER TABLE `ss_user`.`SURVEY_PRE_INITIATION` 
ADD COLUMN `IS_SURVEY_REQUEST_SENT` INT(1) NULL default 0 AFTER `ENGAGEMENT_CLOSED_TIME` ;

update `ss_user`.`SURVEY_PRE_INITIATION` set IS_SURVEY_REQUEST_SENT= 1 where LAST_REMINDER_TIME > '1970-01-02 00:00:00';

