ALTER TABLE `survey_pre_initiation` 
ADD COLUMN `PROPERTY_ADDRESS` VARCHAR(250) NULL DEFAULT NULL AFTER `TRANSACTION_TYPE`,
ADD COLUMN `LOAN_PROCESSOR_NAME` VARCHAR(250) NULL DEFAULT NULL AFTER `PROPERTY_ADDRESS`,
ADD COLUMN `LOAN_PROCESSOR_EMAIL` VARCHAR(250) NULL DEFAULT NULL AFTER `LOAN_PROCESSOR_NAME`;