UPDATE `ss_user`.`SURVEY_QUESTIONS` SET `SURVEY_QUESTIONS_CODE`='sb-range-0to10' WHERE `SURVEY_QUESTIONS_ID`='3';

INSERT INTO `ss_user`.`SURVEY_0TO10_QUESTIONS` (`SURVEY_QUESTIONS_ID`, `IS_NPS_QUESTION`, `CONSIDER_FOR_SCORE`, `NOT_AT_ALL_LIKELY`, `VERY_LIKELY`, `STATUS`, `CREATED_ON`, `MODIFIED_ON`, `CREATED_BY`, `MODIFIED_BY`) VALUES ('3', '1', '1', 'Not Very Likely', 'Very Likely', '1', NOW(), NOW(), '1', '1');
