ALTER TABLE `ss_user`.`SURVEY_PRE_INITIATION` 
ADD COLUMN `CUSTOM_FIELD_ONE` VARCHAR(250) NULL DEFAULT NULL AFTER `LOAN_PROCESSOR_EMAIL`,
ADD COLUMN `CUSTOM_FIELD_TWO` VARCHAR(250) NULL DEFAULT NULL AFTER `CUSTOM_FIELD_ONE`,
ADD COLUMN `CUSTOM_FIELD_THREE` VARCHAR(250) NULL DEFAULT NULL AFTER `CUSTOM_FIELD_TWO`,
ADD COLUMN `CUSTOM_FIELD_FOUR` VARCHAR(250) NULL DEFAULT NULL AFTER `CUSTOM_FIELD_THREE`,
ADD COLUMN `CUSTOM_FIELD_FIVE` VARCHAR(250) NULL DEFAULT NULL AFTER `CUSTOM_FIELD_FOUR`;
