CREATE TABLE `DELETE_DATA_TRACKER` (
  `DELETE_DATA_TRACKER_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ENTITY_ID` varchar(45) NOT NULL,
  `ENTITY_TYPE` varchar(45) NOT NULL,
  `CREATED_ON` timestamp NULL DEFAULT NULL,
  `MODIFIED_ON` timestamp NULL DEFAULT NULL,
  `IS_DELETED` tinyint(4) NOT NULL,
  PRIMARY KEY (`DELETE_DATA_TRACKER_ID`)
);
