ALTER TABLE USERS
ADD COLUMN `ADOPTION_COMPLETION_DATE` TIMESTAMP NULL AFTER `LAST_INVITATION_SENT_DATE`;

ALTER TABLE USERS
ADD COLUMN `LAST_USER_LOGIN` TIMESTAMP NULL DEFAULT NULL AFTER `LAST_LOGIN`; 
