ALTER TABLE SURVEY_PRE_INITIATION ADD COLUMN CUSTOMER_CONTACT_NUMBER  VARCHAR(30) AFTER CUSTOMER_EMAIL_ID;

ALTER TABLE SURVEY_PRE_INITIATION ADD LAST_SMS_REMINDER_TIME TIMESTAMP NULL AFTER LAST_REMINDER_TIME;

ALTER TABLE SURVEY_PRE_INITIATION ADD COLUMN REMINDER_COUNTS_SMS  TINYINT DEFAULT 0 AFTER REMINDER_COUNTS;

ALTER TABLE SURVEY_PRE_INITIATION ADD COLUMN IS_AUTO_SMS_REMINDER_SENT  TINYINT DEFAULT 0 AFTER IS_SURVEY_REQUEST_SENT;
