ALTER TABLE `survey_pre_initiation` 
ADD COLUMN `PARTICIPANT_TYPE` INT(11) NULL DEFAULT 0 AFTER `CUSTOMER_INTERACTION_DETAILS`,
ADD COLUMN `IS_SURVEY_REQUEST_SENT` INT(1) NULL default 0 AFTER `ENGAGEMENT_CLOSED_TIME` ;

update `SURVEY_PRE_INITIATION` set IS_SURVEY_REQUEST_SENT= 1 where LAST_REMINDER_TIME > '1970-01-02 00:00:00';

