CREATE TABLE `survey_stats_report` (
  `survey_stats_report_id` varchar(45) NOT NULL,
  `Id` text,
  `company_id` int(10) unsigned DEFAULT NULL,
  `branch_id` int(10) unsigned DEFAULT NULL,
  `month` varchar(10) DEFAULT NULL,
  `trx_rcvd` int(11) DEFAULT NULL,
  `pending` int(11) DEFAULT NULL,
  `duplicates` int(11) DEFAULT NULL,
  `corrupted` int(11) DEFAULT NULL,
  `abusive` int(11) DEFAULT NULL,
  `old_records` int(11) DEFAULT NULL,
  `ignored` int(11) DEFAULT NULL,
  `mismatched` int(11) DEFAULT NULL,
  `sent_count` int(11) DEFAULT NULL,
  `clicked_count` int(11) DEFAULT NULL,
  `completed` int(11) DEFAULT NULL,
  `partially_completed` int(11) DEFAULT NULL,
  `complete_percentage` float DEFAULT NULL,
  `delta` int(11) DEFAULT NULL,
  `created_date` datetime DEFAULT NULL,
  PRIMARY KEY (`survey_stats_report_id`),
  KEY `FK_BRANCH_idx` (`branch_id`),
  KEY `FK_COMPANY_idx` (`company_id`),
  CONSTRAINT `FK_BRANCH` FOREIGN KEY (`branch_id`) REFERENCES `branch` (`BRANCH_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_COMPANY` FOREIGN KEY (`company_id`) REFERENCES `company` (`COMPANY_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
