ALTER TABLE users 
ADD COLUMN `ADOPTION_COMPLETED_DATE_EST` VARCHAR(450) NULL AFTER `LAST_LOGIN_EST`;

ALTER TABLE users 
ADD COLUMN `ADOPTION_COMPLETED_DATE` TIMESTAMP NULL AFTER `ADOPTION_COMPLETED_DATE_EST`;

ALTER TABLE users
ADD COLUMN `LAST_USER_LOGIN` TIMESTAMP NULL DEFAULT NULL AFTER `ADOPTION_COMPLETED_DATE`,
ADD COLUMN `LAST_USER_LOGIN_EST` VARCHAR(450) NULL AFTER `LAST_USER_LOGIN`;
