ALTER TABLE `overview_branch_month` 
CHANGE COLUMN `branch_id` `branch_id` INT(11) NULL DEFAULT '0' ,
CHANGE COLUMN `processed` `processed` INT(10) NULL DEFAULT '0' ,
CHANGE COLUMN `completed` `completed` INT(10) NULL DEFAULT '0' ,
CHANGE COLUMN `incomplete` `incomplete` INT(10) NULL DEFAULT '0' ,
CHANGE COLUMN `social_posts` `social_posts` INT(10) NULL DEFAULT '0' ,
CHANGE COLUMN `zillow_reviews` `zillow_reviews` INT(10) NULL DEFAULT '0' ,
CHANGE COLUMN `unprocessed` `unprocessed` INT(10) NULL DEFAULT '0' ,
CHANGE COLUMN `unassigned` `unassigned` INT(10) NULL DEFAULT '0' ,
CHANGE COLUMN `duplicate` `duplicate` INT(10) NULL DEFAULT '0' ,
CHANGE COLUMN `corrupted` `corrupted` INT(10) NULL DEFAULT '0' ,
CHANGE COLUMN `other` `other` INT(10) NULL DEFAULT '0' ,
CHANGE COLUMN `complete_percentage` `complete_percentage` DECIMAL(10,2) NULL DEFAULT '0.0' ,
CHANGE COLUMN `incomplete_percentage` `incomplete_percentage` DECIMAL(10,2) NULL DEFAULT '0.0' ,
CHANGE COLUMN `rating` `rating` DECIMAL(10,2) NULL DEFAULT '0.0' ,
CHANGE COLUMN `total_review` `total_review` INT(10) NULL DEFAULT '0' ,
CHANGE COLUMN `month` `month` INT(10) NULL DEFAULT '0' ,
CHANGE COLUMN `year` `year` INT(10) NULL DEFAULT '0' ;

ALTER TABLE `overview_region_month` 
CHANGE COLUMN `region_id` `region_id` INT(11) NULL DEFAULT '0' ,
CHANGE COLUMN `processed` `processed` INT(10) NULL DEFAULT '0' ,
CHANGE COLUMN `completed` `completed` INT(10) NULL DEFAULT '0' ,
CHANGE COLUMN `incomplete` `incomplete` INT(10) NULL DEFAULT '0' ,
CHANGE COLUMN `social_posts` `social_posts` INT(10) NULL DEFAULT '0' ,
CHANGE COLUMN `zillow_reviews` `zillow_reviews` INT(10) NULL DEFAULT '0' ,
CHANGE COLUMN `unprocessed` `unprocessed` INT(10) NULL DEFAULT '0' ,
CHANGE COLUMN `unassigned` `unassigned` INT(10) NULL DEFAULT '0' ,
CHANGE COLUMN `duplicate` `duplicate` INT(10) NULL DEFAULT '0' ,
CHANGE COLUMN `corrupted` `corrupted` INT(10) NULL DEFAULT '0' ,
CHANGE COLUMN `other` `other` INT(10) NULL DEFAULT '0' ,
CHANGE COLUMN `complete_percentage` `complete_percentage` DECIMAL(10,2) NULL DEFAULT '0.0' ,
CHANGE COLUMN `incomplete_percentage` `incomplete_percentage` DECIMAL(10,2) NULL DEFAULT '0.0' ,
CHANGE COLUMN `rating` `rating` DECIMAL(10,2) NULL DEFAULT '0.0' ,
CHANGE COLUMN `total_review` `total_review` INT(10) NULL DEFAULT '0' ,
CHANGE COLUMN `month` `month` INT(10) NULL DEFAULT '0' ,
CHANGE COLUMN `year` `year` INT(10) NULL DEFAULT '0' ;

ALTER TABLE `overview_company_month` 
CHANGE COLUMN `company_id` `company_id` INT(11) NULL DEFAULT '0' ,
CHANGE COLUMN `processed` `processed` INT(10) NULL DEFAULT '0' ,
CHANGE COLUMN `completed` `completed` INT(10) NULL DEFAULT '0' ,
CHANGE COLUMN `incomplete` `incomplete` INT(10) NULL DEFAULT '0' ,
CHANGE COLUMN `social_posts` `social_posts` INT(10) NULL DEFAULT '0' ,
CHANGE COLUMN `zillow_reviews` `zillow_reviews` INT(10) NULL DEFAULT '0' ,
CHANGE COLUMN `unprocessed` `unprocessed` INT(10) NULL DEFAULT '0' ,
CHANGE COLUMN `unassigned` `unassigned` INT(10) NULL DEFAULT '0' ,
CHANGE COLUMN `duplicate` `duplicate` INT(10) NULL DEFAULT '0' ,
CHANGE COLUMN `corrupted` `corrupted` INT(10) NULL DEFAULT '0' ,
CHANGE COLUMN `other` `other` INT(10) NULL DEFAULT '0' ,
CHANGE COLUMN `complete_percentage` `complete_percentage` DECIMAL(10,2) NULL DEFAULT '0.0' ,
CHANGE COLUMN `incomplete_percentage` `incomplete_percentage` DECIMAL(10,2) NULL DEFAULT '0.0' ,
CHANGE COLUMN `rating` `rating` DECIMAL(10,2) NULL DEFAULT '0.0' ,
CHANGE COLUMN `total_review` `total_review` INT(10) NULL DEFAULT '0' ,
CHANGE COLUMN `month` `month` INT(10) NULL DEFAULT '0' ,
CHANGE COLUMN `year` `year` INT(10) NULL DEFAULT '0' ;
