
CREATE TABLE `user_ranking_this_month_main` (
  `user_ranking_this_month_main_id` varchar(36) NOT NULL,
  `user_id` int(11) unsigned DEFAULT NULL,
  `company_id` int(11) unsigned DEFAULT NULL,
  `this_month` int(11) DEFAULT NULL,
  `this_year` int(11) DEFAULT NULL,
  `first_name` varchar(45) DEFAULT NULL,
  `last_name` varchar(45) DEFAULT NULL,
  `ranking_score` decimal(10,2) DEFAULT NULL,
  `rank` int(11) DEFAULT NULL,
  `sps` decimal(10,2) DEFAULT NULL,
  `days_of_registration` int(11) DEFAULT NULL,
  `completed` int(11) DEFAULT NULL,
  `sent` int(11) DEFAULT NULL,
  `completed_percentage` decimal(10,2) DEFAULT NULL,
  `total_reviews` int(11) DEFAULT NULL,
  `is_eligible` tinyint(4) DEFAULT NULL,
  `average_rating` tinyint(4) DEFAULT NULL,
  PRIMARY KEY (`user_ranking_this_month_main_id`),
  KEY `UR_COMPANY_ID_idx` (`company_id`),
  KEY `UR_USER_ID_idx` (`user_id`),
  CONSTRAINT `UR_COMPANY_ID` FOREIGN KEY (`company_id`) REFERENCES `company` (`COMPANY_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `UR_USER_ID` FOREIGN KEY (`user_id`) REFERENCES `users` (`USER_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `user_ranking_this_month_branch` (
  `user_ranking_this_month_branch_id` varchar(36) NOT NULL,
  `user_id` int(11) unsigned DEFAULT NULL,
  `company_id` int(11) unsigned DEFAULT NULL,
  `branch_id` int(11) unsigned DEFAULT NULL,
  `this_month` int(11) DEFAULT NULL,
  `this_year` int(11) DEFAULT NULL,
  `first_name` varchar(45) DEFAULT NULL,
  `last_name` varchar(45) DEFAULT NULL,
  `ranking_score` decimal(10,2) DEFAULT NULL,
  `rank` int(11) DEFAULT NULL,
  `sps` decimal(10,2) DEFAULT NULL,
  `days_of_registration` int(11) DEFAULT NULL,
  `completed` int(11) DEFAULT NULL,
  `sent` int(11) DEFAULT NULL,
  `completed_percentage` decimal(10,2) DEFAULT NULL,
  `total_reviews` int(11) DEFAULT NULL,
  `is_eligible` tinyint(4) DEFAULT NULL,
  `average_rating` tinyint(4) DEFAULT NULL,
  PRIMARY KEY (`user_ranking_this_month_branch_id`),
  KEY `UR1_COMPANY_ID_idx` (`company_id`),
  KEY `UR1_USER_ID_idx` (`user_id`),
  KEY `UR1_BRANCH_ID_idx` (`branch_id`),
  CONSTRAINT `UR1_COMPANY_ID` FOREIGN KEY (`company_id`) REFERENCES `company` (`COMPANY_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `UR1_USER_ID` FOREIGN KEY (`user_id`) REFERENCES `users` (`USER_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
   CONSTRAINT `UR1_BRANCH_ID` FOREIGN KEY (`branch_id`) REFERENCES `branch` (`BRANCH_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `user_ranking_this_month_region` (
  `user_ranking_this_month_region_id` varchar(36) NOT NULL,
  `user_id` int(11) unsigned DEFAULT NULL,
  `company_id` int(11) unsigned DEFAULT NULL,
  `region_id` int(11) unsigned DEFAULT NULL,
  `this_month` int(11) DEFAULT NULL,
  `this_year` int(11) DEFAULT NULL,
  `first_name` varchar(45) DEFAULT NULL,
  `last_name` varchar(45) DEFAULT NULL,
  `ranking_score` decimal(10,2) DEFAULT NULL,
  `rank` int(11) DEFAULT NULL,
  `sps` decimal(10,2) DEFAULT NULL,
  `days_of_registration` int(11) DEFAULT NULL,
  `completed` int(11) DEFAULT NULL,
  `sent` int(11) DEFAULT NULL,
  `completed_percentage` decimal(10,2) DEFAULT NULL,
  `total_reviews` int(11) DEFAULT NULL,
  `is_eligible` tinyint(4) DEFAULT NULL,
  `average_rating` tinyint(4) DEFAULT NULL,
  PRIMARY KEY (`user_ranking_this_month_region_id`),
  KEY `UR2_COMPANY_ID_idx` (`company_id`),
  KEY `UR2_USER_ID_idx` (`user_id`),
  KEY `UR2_REGION_ID_idx` (`region_id`),
  CONSTRAINT `UR2_COMPANY_ID` FOREIGN KEY (`company_id`) REFERENCES `company` (`COMPANY_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `UR2_USER_ID` FOREIGN KEY (`user_id`) REFERENCES `users` (`USER_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `UR2_REGION_ID` FOREIGN KEY (`region_id`) REFERENCES `region` (`REGION_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `user_ranking_this_year_main` (
  `user_ranking_this_year_main_id` varchar(36) NOT NULL,
  `user_id` int(11) unsigned DEFAULT NULL,
  `company_id` int(11) unsigned DEFAULT NULL,
  `this_year` int(11) DEFAULT NULL,
  `first_name` varchar(45) DEFAULT NULL,
  `last_name` varchar(45) DEFAULT NULL,
  `ranking_score` decimal(10,2) DEFAULT NULL,
  `rank` int(11) DEFAULT NULL,
  `sps` decimal(10,2) DEFAULT NULL,
  `days_of_registration` int(11) DEFAULT NULL,
  `completed` int(11) DEFAULT NULL,
  `sent` int(11) DEFAULT NULL,
  `completed_percentage` decimal(10,2) DEFAULT NULL,
  `total_reviews` int(11) DEFAULT NULL,
  `is_eligible` tinyint(4) DEFAULT NULL,
  `average_rating` tinyint(4) DEFAULT NULL,
  PRIMARY KEY (`user_ranking_this_year_main_id`),
  KEY `UR3_COMPANY_ID_idx` (`company_id`),
  KEY `UR3_USER_ID_idx` (`user_id`),
  CONSTRAINT `UR3_COMPANY_ID` FOREIGN KEY (`company_id`) REFERENCES `company` (`COMPANY_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `UR3_USER_ID` FOREIGN KEY (`user_id`) REFERENCES `users` (`USER_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `user_ranking_this_year_branch` (
  `user_ranking_this_year_branch_id` varchar(36) NOT NULL,
  `user_id` int(11) unsigned DEFAULT NULL,
  `company_id` int(11) unsigned DEFAULT NULL,
  `branch_id` int(11) unsigned DEFAULT NULL,
  `this_year` int(11) DEFAULT NULL,
  `first_name` varchar(45) DEFAULT NULL,
  `last_name` varchar(45) DEFAULT NULL,
  `ranking_score` decimal(10,2) DEFAULT NULL,
  `rank` int(11) DEFAULT NULL,
  `sps` decimal(10,2) DEFAULT NULL,
  `days_of_registration` int(11) DEFAULT NULL,
  `completed` int(11) DEFAULT NULL,
  `sent` int(11) DEFAULT NULL,
  `completed_percentage` decimal(10,2) DEFAULT NULL,
  `total_reviews` int(11) DEFAULT NULL,
  `is_eligible` tinyint(4) DEFAULT NULL,
  `average_rating` tinyint(4) DEFAULT NULL,
  PRIMARY KEY (`user_ranking_this_year_branch_id`),
  KEY `UR4_COMPANY_ID_idx` (`company_id`),
  KEY `UR4_USER_ID_idx` (`user_id`),
  KEY `UR4_BRANCH_ID_idx` (`branch_id`),
  CONSTRAINT `UR4_COMPANY_ID` FOREIGN KEY (`company_id`) REFERENCES `company` (`COMPANY_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `UR4_USER_ID` FOREIGN KEY (`user_id`) REFERENCES `users` (`USER_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
   CONSTRAINT `UR4_BRANCH_ID` FOREIGN KEY (`branch_id`) REFERENCES `branch` (`BRANCH_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `user_ranking_this_year_region` (
  `user_ranking_this_year_region_id` varchar(36) NOT NULL,
  `user_id` int(11) unsigned DEFAULT NULL,
  `company_id` int(11) unsigned DEFAULT NULL,
  `region_id` int(11) unsigned DEFAULT NULL,
  `this_year` int(11) DEFAULT NULL,
  `first_name` varchar(45) DEFAULT NULL,
  `last_name` varchar(45) DEFAULT NULL,
  `ranking_score` decimal(10,2) DEFAULT NULL,
  `rank` int(11) DEFAULT NULL,
  `sps` decimal(10,2) DEFAULT NULL,
  `days_of_registration` int(11) DEFAULT NULL,
  `completed` int(11) DEFAULT NULL,
  `sent` int(11) DEFAULT NULL,
  `completed_percentage` decimal(10,2) DEFAULT NULL,
  `total_reviews` int(11) DEFAULT NULL,
  `is_eligible` tinyint(4) DEFAULT NULL,
  `average_rating` tinyint(4) DEFAULT NULL,
  PRIMARY KEY (`user_ranking_this_year_region_id`),
  KEY `UR5_COMPANY_ID_idx` (`company_id`),
  KEY `UR5_USER_ID_idx` (`user_id`),
  KEY `UR5_REGION_ID_idx` (`region_id`),
  CONSTRAINT `UR5_COMPANY_ID` FOREIGN KEY (`company_id`) REFERENCES `company` (`COMPANY_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `UR5_USER_ID` FOREIGN KEY (`user_id`) REFERENCES `users` (`USER_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `UR5_REGION_ID` FOREIGN KEY (`region_id`) REFERENCES `region` (`REGION_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `user_ranking_past_month_main` (
  `user_ranking_past_month_main_id` varchar(36) NOT NULL,
  `user_id` int(11) unsigned DEFAULT NULL,
  `company_id` int(11) unsigned DEFAULT NULL,
  `month` int(11) DEFAULT NULL,
  `year` int(11) DEFAULT NULL,
  `first_name` varchar(45) DEFAULT NULL,
  `last_name` varchar(45) DEFAULT NULL,
  `ranking_score` decimal(10,2) DEFAULT NULL,
  `rank` int(11) DEFAULT NULL,
  `sps` decimal(10,2) DEFAULT NULL,
  `days_of_registration` int(11) DEFAULT NULL,
  `completed` int(11) DEFAULT NULL,
  `sent` int(11) DEFAULT NULL,
  `completed_percentage` decimal(10,2) DEFAULT NULL,
  `total_reviews` int(11) DEFAULT NULL,
  `is_eligible` tinyint(4) DEFAULT NULL,
  `month_year` varchar(45) DEFAULT NULL,
  `average_rating` tinyint(4) DEFAULT NULL,
  PRIMARY KEY (`user_ranking_past_month_main_id`),
  KEY `UR6_COMPANY_ID_idx` (`company_id`),
  KEY `UR6_USER_ID_idx` (`user_id`),
  CONSTRAINT `UR6_COMPANY_ID` FOREIGN KEY (`company_id`) REFERENCES `company` (`COMPANY_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `UR6_USER_ID` FOREIGN KEY (`user_id`) REFERENCES `users` (`USER_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



CREATE TABLE `user_ranking_past_month_branch` (
  `user_ranking_past_month_branch_id` varchar(36) NOT NULL,
  `user_id` int(11) unsigned DEFAULT NULL,
  `company_id` int(11) unsigned DEFAULT NULL,
  `branch_id` int(11) unsigned DEFAULT NULL,
  `month` int(11) DEFAULT NULL,
  `year` int(11) DEFAULT NULL,
  `first_name` varchar(45) DEFAULT NULL,
  `last_name` varchar(45) DEFAULT NULL,
  `ranking_score` decimal(10,2) DEFAULT NULL,
  `rank` int(11) DEFAULT NULL,
  `sps` decimal(10,2) DEFAULT NULL,
  `days_of_registration` int(11) DEFAULT NULL,
  `completed` int(11) DEFAULT NULL,
  `sent` int(11) DEFAULT NULL,
  `completed_percentage` decimal(10,2) DEFAULT NULL,
  `total_reviews` int(11) DEFAULT NULL,
  `is_eligible` tinyint(4) DEFAULT NULL,
  `month_year` varchar(45) DEFAULT NULL,
  `average_rating` tinyint(4) DEFAULT NULL,
  PRIMARY KEY (`user_ranking_past_month_branch_id`),
  KEY `UR61_COMPANY_ID_idx` (`company_id`),
  KEY `UR61_USER_ID_idx` (`user_id`),
  KEY `UR61_BRANCH_ID_idx` (`branch_id`),
  CONSTRAINT `UR61_COMPANY_ID` FOREIGN KEY (`company_id`) REFERENCES `company` (`COMPANY_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `UR61_USER_ID` FOREIGN KEY (`user_id`) REFERENCES `users` (`USER_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
   CONSTRAINT `UR61_BRANCH_ID` FOREIGN KEY (`branch_id`) REFERENCES `branch` (`BRANCH_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `user_ranking_past_month_region` (
  `user_ranking_past_month_region_id` varchar(36) NOT NULL,
  `user_id` int(11) unsigned DEFAULT NULL,
  `company_id` int(11) unsigned DEFAULT NULL,
  `region_id` int(11) unsigned DEFAULT NULL,
  `month` int(11) DEFAULT NULL,
  `year` int(11) DEFAULT NULL,
  `first_name` varchar(45) DEFAULT NULL,
  `last_name` varchar(45) DEFAULT NULL,
  `ranking_score` decimal(10,2) DEFAULT NULL,
  `rank` int(11) DEFAULT NULL,
  `sps` decimal(10,2) DEFAULT NULL,
  `days_of_registration` int(11) DEFAULT NULL,
  `completed` int(11) DEFAULT NULL,
  `sent` int(11) DEFAULT NULL,
  `completed_percentage` decimal(10,2) DEFAULT NULL,
  `total_reviews` int(11) DEFAULT NULL,
  `is_eligible` tinyint(4) DEFAULT NULL,
  `month_year` varchar(45) DEFAULT NULL,
  `average_rating` tinyint(4) DEFAULT NULL,
  PRIMARY KEY (`user_ranking_past_month_region_id`),
  KEY `UR62_COMPANY_ID_idx` (`company_id`),
  KEY `UR62_USER_ID_idx` (`user_id`),
  KEY `UR62_REGION_ID_idx` (`region_id`),
  CONSTRAINT `UR62_COMPANY_ID` FOREIGN KEY (`company_id`) REFERENCES `company` (`COMPANY_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `UR62_USER_ID` FOREIGN KEY (`user_id`) REFERENCES `users` (`USER_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `UR62_REGION_ID` FOREIGN KEY (`region_id`) REFERENCES `region` (`REGION_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `user_ranking_past_year_main` (
  `user_ranking_past_year_main_id` varchar(36) NOT NULL,
  `user_id` int(11) unsigned DEFAULT NULL,
  `company_id` int(11) unsigned DEFAULT NULL,
  `year` int(11) DEFAULT NULL,
  `first_name` varchar(45) DEFAULT NULL,
  `last_name` varchar(45) DEFAULT NULL,
  `ranking_score` decimal(10,2) DEFAULT NULL,
  `rank` int(11) DEFAULT NULL,
  `sps` decimal(10,2) DEFAULT NULL,
  `days_of_registration` int(11) DEFAULT NULL,
  `completed` int(11) DEFAULT NULL,
  `sent` int(11) DEFAULT NULL,
  `completed_percentage` decimal(10,2) DEFAULT NULL,
  `total_reviews` int(11) DEFAULT NULL,
  `is_eligible` tinyint(4) DEFAULT NULL,
  `average_rating` tinyint(4) DEFAULT NULL,
  PRIMARY KEY (`user_ranking_past_year_main_id`),
  KEY `UR63_COMPANY_ID_idx` (`company_id`),
  KEY `UR63_USER_ID_idx` (`user_id`),
  CONSTRAINT `UR63_COMPANY_ID` FOREIGN KEY (`company_id`) REFERENCES `company` (`COMPANY_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `UR63_USER_ID` FOREIGN KEY (`user_id`) REFERENCES `users` (`USER_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `user_ranking_past_year_branch` (
  `user_ranking_past_year_branch_id` varchar(36) NOT NULL,
  `user_id` int(11) unsigned DEFAULT NULL,
  `company_id` int(11) unsigned DEFAULT NULL,
  `branch_id` int(11) unsigned DEFAULT NULL,
  `year` int(11) DEFAULT NULL,
  `first_name` varchar(45) DEFAULT NULL,
  `last_name` varchar(45) DEFAULT NULL,
  `ranking_score` decimal(10,2) DEFAULT NULL,
  `rank` int(11) DEFAULT NULL,
  `sps` decimal(10,2) DEFAULT NULL,
  `days_of_registration` int(11) DEFAULT NULL,
  `completed` int(11) DEFAULT NULL,
  `sent` int(11) DEFAULT NULL,
  `completed_percentage` decimal(10,2) DEFAULT NULL,
  `total_reviews` int(11) DEFAULT NULL,
  `is_eligible` tinyint(4) DEFAULT NULL,
  `average_rating` tinyint(4) DEFAULT NULL,
  PRIMARY KEY (`user_ranking_past_year_branch_id`),
  KEY `UR64_COMPANY_ID_idx` (`company_id`),
  KEY `UR64_USER_ID_idx` (`user_id`),
  KEY `UR64_BRANCH_ID_idx` (`branch_id`),
  CONSTRAINT `UR64_COMPANY_ID` FOREIGN KEY (`company_id`) REFERENCES `company` (`COMPANY_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `UR64_USER_ID` FOREIGN KEY (`user_id`) REFERENCES `users` (`USER_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
   CONSTRAINT `UR64_BRANCH_ID` FOREIGN KEY (`branch_id`) REFERENCES `branch` (`BRANCH_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `user_ranking_past_year_region` (
  `user_ranking_past_year_region_id` varchar(36) NOT NULL,
  `user_id` int(11) unsigned DEFAULT NULL,
  `company_id` int(11) unsigned DEFAULT NULL,
  `region_id` int(11) unsigned DEFAULT NULL,
  `year` int(11) DEFAULT NULL,
  `first_name` varchar(45) DEFAULT NULL,
  `last_name` varchar(45) DEFAULT NULL,
  `ranking_score` decimal(10,2) DEFAULT NULL,
  `rank` int(11) DEFAULT NULL,
  `sps` decimal(10,2) DEFAULT NULL,
  `days_of_registration` int(11) DEFAULT NULL,
  `completed` int(11) DEFAULT NULL,
  `sent` int(11) DEFAULT NULL,
  `completed_percentage` decimal(10,2) DEFAULT NULL,
  `total_reviews` int(11) DEFAULT NULL,
  `is_eligible` tinyint(4) DEFAULT NULL,
  `average_rating` tinyint(4) DEFAULT NULL,
  PRIMARY KEY (`user_ranking_past_year_region_id`),
  KEY `UR65_COMPANY_ID_idx` (`company_id`),
  KEY `UR65_USER_ID_idx` (`user_id`),
  KEY `UR65_REGION_ID_idx` (`region_id`),
  CONSTRAINT `UR65_COMPANY_ID` FOREIGN KEY (`company_id`) REFERENCES `company` (`COMPANY_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `UR65_USER_ID` FOREIGN KEY (`user_id`) REFERENCES `users` (`USER_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `UR65_REGION_ID` FOREIGN KEY (`region_id`) REFERENCES `region` (`REGION_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;