package com.realtech.socialsurvey.core.utils;

// SS-14 By RM02 BOC

/**
 * Class containing variables holding the messages to be displayed in the application
 */
public final class DisplayMessageConstants
{

    private DisplayMessageConstants()
    {}

    // error message constants
    public static final String INVALID_FIRSTNAME = "INVALID_FIRSTNAME";
    public static final String INVALID_LASTNAME = "INVALID_LASTNAME";
    public static final String INVALID_EMAILID = "INVALID_EMAILID";
    public static final String INVALID_ACCOUNT = "INVALID_ACCOUNT";
    public static final String INVALID_CAPTCHA = "INVALID_CAPTCHA";
    public static final String SELF_SURVEY_INITIATION = "SELF_SURVEY_INITIATION";
    public static final String DUPLICATE_SURVEY_REQUEST = "DUPLICATE_SURVEY_REQUEST";
    public static final String REGISTRATION_INVITE_GENERAL_ERROR = "REGISTRATION_INVITE_GENERAL_ERROR";
    public static final String GENERAL_ERROR = "GENERAL_ERROR";
    public static final String INVALID_USERNAME = "INVALID_USERNAME";
    public static final String INVALID_PASSWORD = "INVALID_PASSWORD";
    public static final String PASSWORDS_MISMATCH = "PASSWORDS_MISMATCH";
    public static final String REGISTRATION_GENERAL_ERROR = "REGISTRATION_GENERAL_ERROR";
    public static final String INVALID_REGISTRATION_URL = "INVALID_REGISTRATION_URL";
    public static final String INVALID_COMPANY_NAME = "INVALID_COMPANY_NAME";
    public static final String INVALID_ADDRESS = "INVALID_ADDRESS";
    public static final String INVALID_ZIPCODE = "INVALID_ZIPCODE";
    public static final String INVALID_COMPANY_PHONEN0 = "INVALID_COMPANY_PHONEN0";
    public static final String INVALID_REGISTRATION_INVITE = "INVALID_REGISTRATION_INVITE";
    public static final String USER_LINK_EXPIRED = "USER_LINK_EXPIRED";
    public static final String USERNAME_ALREADY_TAKEN = "USERNAME_ALREADY_TAKEN";
    public static final String EMAILID_ALREADY_TAKEN = "EMAILID_ALREADY_TAKEN";
    public static final String INVALID_USER_CREDENTIALS = "INVALID_USER_CREDENTIALS";
    public static final String INVALID_USER = "INVALID_USER";
    public static final String USER_INACTIVE = "USER_INACTIVE";
    public static final String COMPANY_INACTIVE = "COMPANY_INACTIVE";
    public static final String USER_NOT_PRESENT = "USER_NOT_PRESENT";
    public static final String USER_PRESENT_NOT_REGISTERED = "USER_PRESENT_NOT_REGISTERED";
    public static final String SUBSCRIPTION_UNSUCCESSFUL = "USER_SUBSCRIPTION_UNSUCCESSFUL";
    public static final String INVALID_REGION_NAME = "INVALID_REGION_NAME";
    public static final String INVALID_REGION_ADDRESS = "INVALID_REGION_ADDRESS";
    public static final String INVALID_BRANCH_NAME = "INVALID_BRANCH_NAME";
    public static final String INVALID_BRANCH_ADDRESS = "INVALID_BRANCH_ADDRESS";
    public static final String INVALID_VERIFICATION_URL = "INVALID_VERIFICATION_URL";
    public static final String INVALID_LOGO_FORMAT = "INVALID_LOGO_FORMAT";
    public static final String INVALID_LOGO_DIMENSIONS = "INVALID_LOGO_DIMENSIONS";
    public static final String INVALID_LOGO_SIZE = "INVALID_LOGO_SIZE";
    public static final String INVALID_LOGO_FILE = "INVALID_LOGO_FILE";
    public static final String MAX_USERS_LIMIT_REACHED = "MAX_USERS_LIMIT_REACHED";
    public static final String USER_MANAGEMENT_NOT_AUTHORIZED = "USER_MANAGEMENT_NOT_AUTHORIZED";
    public static final String BRANCH_ASSIGNING_NOT_AUTHORIZED = "BRANCH_ASSIGNING_NOT_AUTHORIZED";
    public static final String NO_USER_IN_SESSION = "NO_USER_IN_SESSION";
    public static final String USER_SEARCH_SUCCESSFUL = "USER_SEARCH_SUCCESSFUL";
    public static final String SESSION_EXPIRED = "SESSION_EXPIRED";
    public static final String INVALID_COUNTRY = "INVALID_COUNTRY";
    public static final String INVALID_VERTICAL = "INVALID_VERTICAL";
    public static final String INVALID_COMPANY_PROFILENAME = "INVALID_COMPANY_PROFILENAME";
    public static final String INVALID_REGION_PROFILENAME = "INVALID_REGION_PROFILENAME";
    public static final String INVALID_BRANCH_PROFILENAME = "INVALID_BRANCH_PROFILENAME";
    public static final String INVALID_INDIVIDUAL_PROFILENAME = "INVALID_INDIVIDUAL_PROFILENAME";
    public static final String INVALID_PROFILE_LEVEL = "INVALID_PROFILE_LEVEL";
    public static final String INVALID_USER_SELECTED = "INVALID_USER_SELECTED";
    public static final String BRANCH_USER_ASSIGNMENT_ERROR = "BRANCH_USER_ASSIGNMENT_ERROR";
    public static final String REGION_USER_ASSIGNMENT_ERROR = "REGION_USER_ASSIGNMENT_ERROR";
    public static final String INVALID_INDIVIDUAL_NAME = "INVALID_INDIVIDUAL_NAME";
    public static final String HIERARCHY_MANAGEMENT_NOT_AUTHORIZED = "HIERARCHY_MANAGEMENT_NOT_AUTHORIZED";
    public static final String USER_ASSIGNMENT_ALREADY_EXISTS = "USER_ASSIGNMENT_ALREADY_EXISTS";
    public static final String INVALID_FIRSTORLAST_NAME_PATTERN = "INVALID_FIRSTORLAST_NAME_PATTERN";

    public static final String INVALID_REGION_SELECTED = "INVALID_REGION_SELECTED";
    public static final String INVALID_SURVEY_REMINDER_INTERVAL = "INVALID_SURVEY_REMINDER_INTERVAL";
    public static final String SUBSCRIPTION_UPGRADE_UNSUCCESSFUL = "SUBSCRIPTION_UPGRADE_UNSUCCESSFUL";
    public static final String SUBSCRIPTION_PAST_DUE = "SUBSCRIPTION_PAST_DUE";
    public static final String INVALID_CURRENT_PASSWORD = "INVALID_CURRENT_PASSWORD";
    public static final String INVALID_NEW_PASSWORD = "INVALID_NEW_PASSWORD";
    public static final String INVALID_CONFIRM_NEW_PASSWORD = "INVALID_CONFIRM_NEW_PASSWORD";
    public static final String PAYMENT_GATEWAY_EXCEPTION = "PAYMENT_GATEWAY_EXCEPTION";
    public static final String CARD_UPDATE_UNSUCCESSFUL = "CARD_UPDATE_UNSUCCESSFUL";
    public static final String CREDIT_CARD_INVALID = "CREDIT_CARD_INVALID";
    public static final String INVALID_SURVEY_ANSWER = "INVALID_SURVEY_ANSWER";
    public static final String NO_SURVEY_FOUND = "NO_SURVEY_FOUND";

    public static final String LOCK_UPDATE_UNSUCCESSFUL = "LOCK_UPDATE_UNSUCCESSFUL";
    public static final String ABOUT_ME_DETAILS_UPDATE_UNSUCCESSFUL = "ABOUT_ME_DETAILS_UPDATE_UNSUCCESSFUL";
    public static final String BASIC_DETAILS_UPDATE_UNSUCCESSFUL = "BASIC_DETAILS_UPDATE_UNSUCCESSFUL";
    public static final String PROFILE_ADDRESSES_UPDATE_UNSUCCESSFUL = "PROFILE_ADDRESSES_UPDATE_UNSUCCESSFUL";
    public static final String LOGO_UPLOAD_UNSUCCESSFUL = "LOGO_UPLOAD_UNSUCCESSFUL";
    public static final String PROFILE_IMAGE_UPLOAD_UNSUCCESSFUL = "PROFILE_IMAGE_UPLOAD_UNSUCCESSFUL";
    public static final String MAIL_IDS_UPDATE_UNSUCCESSFUL = "MAIL_IDS_UPDATE_UNSUCCESSFUL";
    public static final String CONTACT_NUMBERS_UPDATE_UNSUCCESSFUL = "CONTACT_NUMBERS_UPDATE_UNSUCCESSFUL";
    public static final String WEB_ADDRESSES_UPDATE_UNSUCCESSFUL = "WEB_ADDRESSES_UPDATE_UNSUCCESSFUL";
    public static final String FACEBOOK_TOKEN_UPDATE_UNSUCCESSFUL = "FACEBOOK_TOKEN_UPDATE_UNSUCCESSFUL";
    public static final String TWITTER_TOKEN_UPDATE_UNSUCCESSFUL = "TWITTER_TOKEN_UPDATE_UNSUCCESSFUL";
    public static final String LINKEDIN_TOKEN_UPDATE_UNSUCCESSFUL = "LINKEDIN_TOKEN_UPDATE_UNSUCCESSFUL";
    public static final String YELP_TOKEN_UPDATE_UNSUCCESSFUL = "YELP_TOKEN_UPDATE_UNSUCCESSFUL";
    public static final String GPLUS_TOKEN_UPDATE_UNSUCCESSFUL = "GPLUS_TOKEN_UPDATE_UNSUCCESSFUL";
    public static final String ZILLOW_TOKEN_UPDATE_UNSUCCESSFUL = "ZILLOW_TOKEN_UPDATE_UNSUCCESSFUL";
    public static final String LENDINGTREE_TOKEN_UPDATE_UNSUCCESSFUL = "LENDINGTREE_TOKEN_UPDATE_UNSUCCESSFUL";
    public static final String FACEBOOK_PIXEL_UPDATE_UNSUCCESSFUL = "FACEBOOK_PIXEL_UPDATE_UNSUCCESSFUL";
    public static final String REALTOR_TOKEN_UPDATE_UNSUCCESSFUL = "REALTOR_TOKEN_UPDATE_UNSUCCESSFUL";
    public static final String GOOGLE_BUSINESS_TOKEN_UPDATE_UNSUCCESSFUL = "GOOGLE_BUSINESS_TOKEN_UPDATE_UNSUCCESSFUL";
    public static final String ASSOCIATION_UPDATE_UNSUCCESSFUL = "ASSOCIATION_UPDATE_UNSUCCESSFUL";
    public static final String ACHIEVEMENT_UPDATE_UNSUCCESSFUL = "ACHIEVEMENT_UPDATE_UNSUCCESSFUL";
    public static final String LICENSES_UPDATE_UNSUCCESSFUL = "LICENSES_UPDATE_UNSUCCESSFUL";
    public static final String HIERARCHY_EDIT_NOT_AUTHORIZED = "HIERARCHY_EDIT_NOT_AUTHORIZED";
    public static final String CONTACT_US_MESSAGE_UNSUCCESSFUL = "CONTACT_US_MESSAGE_UNSUCCESSFUL";
    public static final String REDUNDANT_ASSIGNMANT = "REDUNDANT_ASSIGNMANT";

    public static final String EXPERTISE_UPDATE_SUCCESSFUL = "EXPERTISE_UPDATE_SUCCESSFUL";
    public static final String EXPERTISE_UPDATE_UNSUCCESSFUL = "EXPERTISE_UPDATE_UNSUCCESSFUL";
    public static final String HOBBIES_UPDATE_SUCCESSFUL = "HOBBIES_UPDATE_SUCCESSFUL";
    public static final String HOBBIES_UPDATE_UNSUCCESSFUL = "HOBBIES_UPDATE_UNSUCCESSFUL";
    public static final String SAVE_STATUS_UNSUCCESSFUL = "SAVE_STATUS_UNSUCCESSFUL";
    public static final String FETCH_SOCIAL_POSTS_UNSUCCESSFUL = "FETCH_SOCIAL_POSTS_UNSUCCESSFUL";
    public static final String BANK_REJECTED = "BANK_REJECTED";
    public static final String ACCOUNT_DELETION_UNSUCCESSFUL = "ACCOUNT_DELETION_UNSUCCESSFUL";
    public static final String DISCLAIMER_UPDATE_UNSUCCESSFUL = "DISCLAIMER_UPDATE_UNSUCCESSFUL";
    public static final String ERROR_IN_SENDING_HELP_MESSAGE = "ERROR_IN_SENDING_HELP_MESSAGE";
    public static final String NOT_ABLE_TO_DELETE_USER_PROFILE = "NOT_ABLE_TO_DELETE_USER_PROFILE";
    public static final String FETCH_UNMATCHED_PREINITIATED_SURVEYS_UNSUCCESSFUL = "FETCH_UNMATCHED_PREINITIATED_SURVEYS_UNSUCCESSFUL";
    public static final String FETCH_CORRUPT_PREINITIATED_SURVEYS_UNSUCCESSFUL = "FETCH_CORRUPT_PREINITIATED_SURVEYS_UNSUCCESSFUL";
    public static final String FETCH_PROCESSED_PREINITIATED_SURVEYS_UNSUCCESSFUL = "FETCH_PROCESSED_PREINITIATED_SURVEYS_UNSUCCESSFUL";
    public static final String ADD_EMAIL_ID_FOR_USER__UNSUCCESSFUL = "ADD_EMAIL_ID_FOR_USER__UNSUCCESSFUL";
    public static final String FETCH_USER_FOR_EMAIL_MAPPING_UNSUCCESSFUL = "FETCH_USER_FOR_EMAIL_MAPPING_UNSUCCESSFUL";
    public static final String FETCH_EMAIL_MAPPINGS_FOR_USER_UNSUCCESSFUL = "FETCH_EMAIL_MAPPINGS_FOR_USER_UNSUCCESSFUL";
    public static final String DELETE_EMAIL_MAPPINGS_UNSUCCESSFUL = "DELETE_EMAIL_MAPPINGS_UNSUCCESSFUL";

    // success message constants
    public static final String HELP_MESSAGE_SUCCESSFULLY_SEND = "HELP_MESSAGE_SUCCESSFULLY_SEND";
    public static final String REGISTRATION_INVITE_SUCCESSFUL = "REGISTRATION_INVITE_SUCCESSFUL";
    public static final String USER_REGISTRATION_SUCCESSFUL = "USER_REGISTRATION_SUCCESSFUL";
    public static final String ACCOUNT_TYPE_SELECTION_SUCCESSFUL = "ACCOUNT_TYPE_SELECTION_SUCCESSFUL";
    public static final String PASSWORD_RESET_LINK_SUCCESSFUL = "PASSWORD_RESET_LINK_SUCCESSFUL";
    public static final String PASSWORD_CHANGE_SUCCESSFUL = "PASSWORD_CHANGE_SUCCESSFUL";
    public static final String USER_LOGIN_SUCCESSFUL = "USER_LOGIN_SUCCESSFUL";
    public static final String SUBSCRIPTION_SUCCESSFUL = "USER_SUBSCRIPTION_SUCCESSFUL";
    public static final String BRANCH_DELETE_SUCCESSFUL = "BRANCH_DELETE_SUCCESSFUL";
    public static final String REGION_DELETE_SUCCESSFUL = "REGION_DELETE_SUCCESSFUL";
    public static final String EMAIL_VERIFICATION_SUCCESSFUL = "EMAIL_VERIFICATION_SUCCESSFUL";
    public static final String EMAIL_VERIFICATION_BY_ADMIN_SUCCESSFUL = "EMAIL_VERIFICATION_BY_ADMIN_SUCCESSFUL";
    public static final String USER_DELETE_SUCCESSFUL = "USER_DELETE_SUCCESSFUL";
    public static final String USER_STATUS_UPDATE_SUCCESSFUL = "USER_STATUS_UPDATE_SUCCESSFUL";
    public static final String BRANCH_UNASSIGN_SUCCESSFUL = "BRANCH_UNASSIGN_SUCCESSFUL";
    public static final String BRANCH_ASSIGN_SUCCESSFUL = "BRANCH_ASSIGN_SUCCESSFUL";
    public static final String BRANCH_ADDITION_SUCCESSFUL = "BRANCH_ADDITION_SUCCESSFUL";
    public static final String INDIVIDUAL_ADDITION_SUCCESSFUL = "INDIVIDUAL_ADDITION_SUCCESSFUL";
    public static final String INDIVIDUAL_MULTIPLE_ADDITION_SUCCESSFUL = "INDIVIDUAL_MULTIPLE_ADDITION_SUCCESSFUL";
    public static final String INDIVIDUAL_MULTIPLE_ADDITION_UNSUCCESSFUL = "INDIVIDUAL_MULTIPLE_ADDITION_UNSUCCESSFUL";
    public static final String REGION_ADDTION_SUCCESSFUL = "REGION_ADDTION_SUCCESSFUL";
    public static final String REGION_UPDATION_SUCCESSFUL = "REGION_UPDATION_SUCCESSFUL";
    public static final String BRANCH_UPDATION_SUCCESSFUL = "BRANCH_UPDATION_SUCCESSFUL";
    public static final String ENCOMPASS_CONNECTION_SUCCESSFUL = "ENCOMPASS_CONNECTION_SUCCESSFUL";
    public static final String ENCOMPASS_ENABLE_SUCCESSFUL = "ENCOMPASS_ENABLE_SUCCESSFUL";
    public static final String ENCOMPASS_DISABLE_SUCCESSFUL = "ENCOMPASS_DISABLE_SUCCESSFUL";
    public static final String ENCOMPASS_GENERATE_REPORT_SUCCESSFUL = "ENCOMPASS_GENERATE_REPORT_SUCCESSFUL";
    public static final String DOTLOOP_CONNECTION_SUCCESSFUL = "DOTLOOP_CONNECTION_SUCCESSFUL";
    public static final String ENCOMPASS_DATA_UPDATE_SUCCESSFUL = "ENCOMPASS_DATA_UPDATE_SUCCESSFUL";
    public static final String DOTLOOP_DATA_UPDATE_SUCCESSFUL = "DOTLOOP_DATA_UPDATE_SUCCESSFUL";
    public static final String SURVEY_PARTICIPATION_MAILBODY_UPDATE_SUCCESSFUL = "SURVEY_PARTICIPATION_MAILBODY_UPDATE_SUCCESSFUL";
    public static final String SURVEY_PARTICIPATION_REMINDERMAILBODY_UPDATE_SUCCESSFUL = "SURVEY_PARTICIPATION_REMINDERMAILBODY_UPDATE_SUCCESSFUL";
    public static final String SURVEY_COMPLETION_MAILBODY_UPDATE_SUCCESSFUL = "SURVEY_COMPLETION_MAILBODY_UPDATE_SUCCESSFUL";
    public static final String SURVEY_COMPLETION_UNPLEASANT_MAILBODY_UPDATE_SUCCESSFUL = "SURVEY_COMPLETION_UNPLEASANT_MAILBODY_UPDATE_SUCCESSFUL";
    public static final String SOCIAL_POST_REMINDER_MAILBODY_UPDATE_SUCCESSFUL = "SOCIAL_POST_REMINDER_MAILBODY_UPDATE_SUCCESSFUL";
    public static final String RESTART_SURVEY_MAILBODY_UPDATE_SUCCESSFUL = "RESTART_SURVEY_MAILBODY_UPDATE_SUCCESSFUL";
    public static final String UNMARK_ABUSIVE_SURVEY_SUCCESSFUL = "UNMARK_ABUSIVE_SURVEY_SUCCESSFUL";

    public static final String SURVEY_AUTO_POST_SCORE_UPDATE_SUCCESSFUL = "SURVEY_AUTO_POST_SCORE_UPDATE_SUCCESSFUL";
    public static final String SURVEY_MIN_POST_SCORE_UPDATE_SUCCESSFUL = "SURVEY_MIN_POST_SCORE_UPDATE_SUCCESSFUL";
    public static final String SURVEY_REMINDER_INTERVAL_UPDATE_SUCCESSFUL = "SURVEY_REMINDER_INTERVAL_UPDATE_SUCCESSFUL";
    public static final String SURVEY_REMINDER_COUNT_UPDATE_SUCCESSFUL = "SURVEY_REMINDER_COUNT_UPDATE_SUCCESSFUL";
    public static final String SURVEY_REMINDER_ENABLED_UPDATE_SUCCESSFUL = "SURVEY_REMINDER_ENABLED_UPDATE_SUCCESSFUL";
    public static final String SOCIAL_POST_REMINDER_INTERVAL_UPDATE_SUCCESSFUL = "SOCIAL_POST_REMINDER_INTERVAL_UPDATE_SUCCESSFUL";
    public static final String SOCIAL_POST_REMINDER_ENABLED_UPDATE_SUCCESSFUL = "SOCIAL_POST_REMINDER_ENABLED_UPDATE_SUCCESSFUL";
    public static final String LOCATION_SETTINGS_UPDATE_SUCCESSFUL = "LOCATION_SETTINGS_UPDATE_SUCCESSFUL";
    public static final String ACCOUNT_SETTINGS_UPDATE_SUCCESSFUL = "ACCOUNT_SETTINGS_UPDATE_SUCCESSFUL";
    public static final String COMPLAINT_REGISTRATION_SUCCESSFUL = "COMPLAINT_REGISTRATION_SUCCESSFUL";
    public static final String ABUSIVE_EMAIL_SUCCESSFUL = "ABUSIVE_EMAIL_SUCCESSFUL";
    public static final String USER_LOGOUT_SUCCESSFUL = "USER_LOGOUT_SUCCESSFUL";
    public static final String TO_INDIVIDUAL_SUBSCRIPTION_UPGRADE_SUCCESSFUL = "TO_INDIVIDUAL_SUBSCRIPTION_UPGRADE_SUCCESSFUL";
    public static final String TO_TEAM_SUBSCRIPTION_UPGRADE_SUCCESSFUL = "TO_TEAM_SUBSCRIPTION_UPGRADE_SUCCESSFUL";
    public static final String TO_COMPANY_SUBSCRIPTION_UPGRADE_SUCCESSFUL = "TO_COMPANY_SUBSCRIPTION_UPGRADE_SUCCESSFUL";
    public static final String TO_ENTERPRISE_SUBSCRIPTION_UPGRADE_SUCCESSFUL = "TO_ENTERPRISE_SUBSCRIPTION_UPGRADE_SUCCESSFUL";
    public static final String CARD_UPDATE_SUCCESSFUL = "CARD_UPDATE_SUCCESSFUL";
    public static final String SUBSCRIPTION_UPGRADE_SUCCESSFUL = "SUBSCRIPTION_UPGRADE_SUCCESSFUL";
    public static final String INVITATION_RESEND_SUCCESSFUL = "INVITATION_RESEND_SUCCESSFUL";
    public static final String PROFILE_UPDATE_SUCCESSFUL = "PROFILE_UPDATE_SUCCESSFUL";
    public static final String ACCOUNT_DELETION_SUCCESSFUL = "ACCOUNT_DELETION_SUCCESSFUL";

    public static final String STATUS_DELETED_SUCCESSFULLY = "STATUS_DELETED_SUCCESSFULLY";
    public static final String STATUS_CAN_NOT_BE_DELETED = "STATUS_CAN_NOT_BE_DELETED";

    public static final String SURVEY_CREATION_SUCCESSFUL = "SURVEY_CREATION_SUCCESSFUL";
    public static final String SURVEY_ALREADY_EXISTS = "SURVEY_ALREADY_EXISTS";
    public static final String SURVEY_QUESTION_MAPPING_SUCCESSFUL = "SURVEY_QUESTION_MAPPING_SUCCESSFUL";
    public static final String SURVEY_QUESTION_MODIFY_SUCCESSFUL = "SURVEY_QUESTION_MODIFY_SUCCESSFUL";
    public static final String SURVEY_QUESTION_DISABLE_SUCCESSFUL = "SURVEY_QUESTION_DISABLE_SUCCESSFUL";
    public static final String SURVEY_QUESTIONS_DISABLE_SUCCESSFUL = "SURVEY_QUESTIONS_DISABLE_SUCCESSFUL";
    public static final String SURVEY_QUESTION_REORDER_SUCCESSFUL = "SURVEY_QUESTION_REORDER_SUCCESSFUL";
    public static final String SURVEY_COMPANY_DISABLE_SUCCESSFUL = "SURVEY_COMPANY_DISABLE_SUCCESSFUL";
    public static final String SURVEY_TEMPLATE_CLONE_SUCCESSFUL = "SURVEY_TEMPLATE_CLONE_SUCCESSFUL";

    public static final String LOCK_UPDATE_SUCCESSFUL = "LOCK_UPDATE_SUCCESSFUL";
    public static final String ABOUT_ME_DETAILS_UPDATE_SUCCESSFUL = "ABOUT_ME_DETAILS_UPDATE_SUCCESSFUL";
    public static final String BASIC_DETAILS_UPDATE_SUCCESSFUL = "BASIC_DETAILS_UPDATE_SUCCESSFUL";
    public static final String PROFILE_ADDRESSES_UPDATE_SUCCESSFUL = "PROFILE_ADDRESSES_UPDATE_SUCCESSFUL";
    public static final String LOGO_UPLOAD_SUCCESSFUL = "LOGO_UPLOAD_SUCCESSFUL";
    public static final String PROFILE_IMAGE_UPLOAD_SUCCESSFUL = "PROFILE_IMAGE_UPLOAD_SUCCESSFUL";
    public static final String MAIL_IDS_UPDATE_SUCCESSFUL = "MAIL_IDS_UPDATE_SUCCESSFUL";
    public static final String MAIL_IDS_UPDATE_REQUEST_SUCCESSFUL = "MAIL_IDS_UPDATE_REQUEST_SUCCESSFUL";
    public static final String CONTACT_NUMBERS_UPDATE_SUCCESSFUL = "CONTACT_NUMBERS_UPDATE_SUCCESSFUL";
    public static final String WEB_ADDRESSES_UPDATE_SUCCESSFUL = "WEB_ADDRESSES_UPDATE_SUCCESSFUL";
    public static final String FACEBOOK_TOKEN_UPDATE_SUCCESSFUL = "FACEBOOK_TOKEN_UPDATE_SUCCESSFUL";
    public static final String TWITTER_TOKEN_UPDATE_SUCCESSFUL = "TWITTER_TOKEN_UPDATE_SUCCESSFUL";
    public static final String LINKEDIN_TOKEN_UPDATE_SUCCESSFUL = "LINKEDIN_TOKEN_UPDATE_SUCCESSFUL";
    public static final String YELP_TOKEN_UPDATE_SUCCESSFUL = "YELP_TOKEN_UPDATE_SUCCESSFUL";
    public static final String GPLUS_TOKEN_UPDATE_SUCCESSFUL = "GPLUS_TOKEN_UPDATE_SUCCESSFUL";
    public static final String ZILLOW_TOKEN_UPDATE_SUCCESSFUL = "ZILLOW_TOKEN_UPDATE_SUCCESSFUL";
    public static final String LENDINGTREE_TOKEN_UPDATE_SUCCESSFUL = "LENDINGTREE_TOKEN_UPDATE_SUCCESSFUL";
    public static final String FACEBOOK_PIXEL_UPDATE_SUCCESSFUL = "FACEBOOK_PIXEL_UPDATE_SUCCESSFUL";
    public static final String REALTOR_TOKEN_UPDATE_SUCCESSFUL = "REALTOR_TOKEN_UPDATE_SUCCESSFUL";
    public static final String GOOGLE_BUSINESS_TOKEN_UPDATE_SUCCESSFUL = "GOOGLE_BUSINESS_TOKEN_UPDATE_SUCCESSFUL";
    public static final String ASSOCIATION_UPDATE_SUCCESSFUL = "ASSOCIATION_UPDATE_SUCCESSFUL";
    public static final String ACHIEVEMENT_UPDATE_SUCCESSFUL = "ACHIEVEMENT_UPDATE_SUCCESSFUL";
    public static final String LICENSES_UPDATE_SUCCESSFUL = "LICENSES_UPDATE_SUCCESSFUL";
    public static final String CONTACT_US_MESSAGE_SENT = "CONTACT_US_MESSAGE_SENT";
    public static final String DISCLAIMER_UPDATE_SUCCESSFUL = "DISCLAIMER_UPDATE_SUCCESSFUL";
    public static final String EMAIL_ID_UPDATE_UNSUCCESSFUL = "EMAIL_ID_UPDATE_UNSUCCESSFUL";
    public static final String ADD_EMAIL_ID_FOR_USER__SUCCESSFUL = "ADD_EMAIL_ID_FOR_USER__SUCCESSFUL";
    public static final String UPDATE_EMAIL_MAPPING_FOR_USER__SUCCESSFUL = "UPDATE_EMAIL_MAPPING_FOR_USER__SUCCESSFUL";

    //Realtech admin module
    public static final String COMPANY_NOT_REGISTERD = "COMPANY_NOT_REGISTERD";
    public static final String SS_ADMIN_DELETE_SUCCESSFUL = "SS_ADMIN_DELETE_SUCCESSFUL";

    public static final String API_STATUS_UPDATE_SUCCESSFUL = "API_STATUS_UPDATE_SUCCESSFUL";


    public static final String TRY_AGAIN = "TRY_AGAIN";
    public static final String INVALID_DETAILS_PROVIDED = "INVALID_DETAILS_PROVIDED";
    public static final String INVALID_API_SECRET = "INVALID_API_SECRET";
    public static final String INVALID_API_KEY = "INVALID_API_KEY";
    public static final String INVALID_COMPANY_ID = "INVALID_COMPANY_ID";
    public static final String INVALID_SURVEY_JSON = "INVALID_SURVEY_JSON";
    public static final String INVALID_AUTHORIZATION_HEADER = "INVALID_AUTHORIZATION_HEADER";
    public static final String INACTIVE_COMPANY_ID = "INACTIVE_COMPANY_ID";

    public static final String INVALID_SOCIAL_POST_REMINDER_ERROR = "INVALID_SOCIAL_POST_REMINDER_ERROR";
    public static final String SUCCESSFULLY_CREATED_SS_ADMIN = "SUCCESSFULLY_CREATED_SS_ADMIN";

    public static final String LONEWOLF_CONNECTION_SUCCESSFUL = "LONEWOLF_CONNECTION_SUCCESSFUL";
    public static final String LONEWOLF_DETAIL_SAVED_SUCCESSFUL = "LONEWOLF_DETAIL_SAVED_SUCCESSFUL";
    public static final String LONEWOLF_ENABLE_SUCCESSFUL = "LONEWOLF_ENABLE_SUCCESSFUL";
    public static final String LONEWOLF_DISABLE_SUCCESSFUL = "LONEWOLF_DISABLE_SUCCESSFUL";
    public static final String LONEWOLF_GENERATE_REPORT_SUCCESSFUL = "LONEWOLF_GENERATE_REPORT_SUCCESSFUL";

    //vendasta message constants
    public static final String UPDATING_VENDASTA_SETTINGS_SUCCESSFUL = "UPDATING_VENDASTA_SETTINGS_SUCCESSFUL";
    public static final String INVALID_VALUES = "INVALID_VALUES";
    public static final String ACCOUNT_DOESNT_EXIST = "ACCOUNT_DOESNT_EXIST";
    public static final String VENDASTA_NOT_FOR_AGENT = "VENDASTA_NOT_FOR_AGENT";

    //sort criteria settings constants
    public static final String INSUFFICIENT_USER_PERMISSION = "INSUFFICIENT_USER_PERMISSION";
    public static final String SORT_CRITERIA_SUCCESSFULLY_UPDATED = "SORT_CRITERIA_SUCCESSFULLY_UPDATED";
    public static final String SEND_EMAIL_THROUGH_SUCCESSFULLY_UPDATED = "SEND_EMAIL_THROUGH_SUCCESSFULLY_UPDATED";
    public static final String SEND_EMAIL_THROUGH_UNSUCCESSFULLY_UPDATED = "SEND_EMAIL_THROUGH_UNSUCCESSFULLY_UPDATED";

    //email criteria
    public static final String INSUFFICIENT_SENDGRID_USER_PERMISSION = "INSUFFICIENT_SENDGRID_USER_PERMISSION";

    // profile image edit 
    public static final String PROFILE_IMAGE_DELETE_SUCCESSFUL = "PROFILE_IMAGE_DELETE_SUCCESSFUL";
    public static final String PROFILE_IMAGE_DELETE_UNSUCCESSFUL = "PROFILE_IMAGE_DELETE_UNSUCCESSFUL";

    //Social Monitor
    public static final String ADD_MONITOR_SUCCESSFUL = "SUCCESSFULLY ADDED MONITOR";
    public static final String ADD_MONITOR_UNSUCCESSFUL = "UNABLE TO ADD MONITOR";
    
    public static final String ADD_MACRO_SUCCESSFUL = "SUCCESSFULLY ADDED MACRO";
    public static final String ADD_MACRO_UNSUCCESSFUL = "UNABLE TO ADD MACRO";
    
    public static final String UPDATE_POST_SUCCESSFUL = "SUCCESSFULLY UPDATED POST";
    public static final String UPDATE_POST_UNSUCCESSFUL = "UNABLE TO UPDATE POST";
}

